### ISSUE TITLE
useState issue 

### ISSUE THREAD

**Issue by issaouimuhamedaziz** [chintan9/plyr-react#1017]
Whenever i use useState inside the page where I have set up Plyr with HLS it changes the Plyr classes and state I think? and breaks the whole page after pressing it twice.

**Comment by realamirhe** [comment]
could you use the usePlyr and look at the HLS component, for re-rendering you must be in the same depth with the `<Plyr />` component itself, Plyr is best for static usage.

https://github.com/chintan9/plyr-react/blob/master/example/react/src/hls-player/custom-hls-player.tsx

**Comment by issaouimuhamedaziz** [comment]
> could you use the usePlyr and look at the HLS component, for re-rendering you must be in the same depth with the `<Plyr />` component itself, Plyr is best for static usage.
> 
> https://github.com/chintan9/plyr-react/blob/master/example/react/src/hls-player/custom-hls-player.tsx

hello, thank you so much your provided solution works perfectly.
