### ISSUE TITLE
plyr 3.7.7 is out there

### ISSUE THREAD

**Issue by realamirhe** [chintan9/plyr-react#1044]
We might need to update the plyr in plyr-react to 3.77

**Comment by tomtang1122** [comment]
+1

**Comment by tomtang1122** [comment]
> We might need to update the plyr in plyr-react to 3.77

+1

**Comment by tomtang1122** [comment]
Approximately when?

**Comment by realamirhe** [comment]
@chintan9, I made a pull request for this update
https://github.com/chintan9/plyr-react/pull/1045

**Comment by chintan9** [comment]
this week
