### ISSUE TITLE
How to run the methods like play, pause, etc.? 

### ISSUE THREAD

**Issue by SoldierCorp** [chintan9/plyr-react#128]

**Comment by rommelmamedov** [comment]
@SoldierCorp Hi! Did you find out how to run these methods?

**Comment by SoldierCorp** [comment]
@rommelmamedov No sorry, I gave up on this library and I used react-player instead

**Comment by rommelmamedov** [comment]
Thank you! I checked the source code there is no available methods for this action in current component.

**Comment by chintan9** [comment]
@SoldierCorp We publish new lib checkout

**Comment by SoldierCorp** [comment]
Thank you @chintan9!
