### ISSUE TITLE
Unable to Import in NextJS -> Bundled CSS

### ISSUE THREAD

**Issue by tommyboylab** [chintan9/plyr-react#162]
**Describe the bug**
Plyr is unable to be imported into a NextJS project as it contains bundled CSS.. Something that is not allowed as documented here.

https://github.com/zeit/next.js/blob/canary/errors/css-modules-npm.md

**To Reproduce**
Install plyr-react in a NextJS project
Import it to a file
Run the development server
See Error

**Expected behaviour**
I should be able to import the project, and supply the CSS separately to my file to avoid this incompatibility

**Comment by chintan9** [comment]
@tommyboylab  Can you share sample repo probably using gitpod

**Comment by chintan9** [comment]
@tommyboylab  Can you retest it v3 again ?

**Comment by chintan9** [comment]
@all-contributors please add @tommyboylab for Bug reports

**Comment by tommyboylab** [comment]
I'll look to re-implement it, confirm if it's working or not once I do. :+1:
