### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by lvndry** [chintan9/plyr-react#201]
Is there any plan to have support for Typescript?

**Comment by chintan9** [comment]
It should work for typescript.  If it is not then you can share with me.

**Comment by madwyn** [comment]
It doesn't work with TypeScript, would you please help to fix?

```
TS7016: Could not find a declaration file for module 'plyr-react'. '/Users/xxx/projects/myApp/node_modules/plyr-react/dist/index.js' implicitly has an 'any' type.   Try `npm install @types/plyr-react` if it exists or add a new declaration (.d.ts) file containing `declare module 'plyr-react';
```

**Comment by madwyn** [comment]
Thanks for your work.

When using plyr-react with Ionic and TypeScript, it won't import and gives the following error:

```
TS7016: Could not find a declaration file for module 'plyr-react'. '/Users/xxx/projects/myApp/node_modules/plyr-react/dist/index.js' implicitly has an 'any' type.   Try `npm install @types/plyr-react` if it exists or add a new declaration (.d.ts) file containing `declare module 'plyr-react';`
```

I'm not a TypeScript expert, but it seems there are many ways to resolve this:
https://blog.atomist.com/declaration-file-fix/

**Comment by chintan9** [comment]
Use this way 
https://stackoverflow.com/questions/55795060/how-to-import-js-in-ts-with-noimplicityany-and-without-allowjs

**Comment by madwyn** [comment]
Thanks for the prompt feedback.

I know there are workarounds, but I'm wondering if this can be implemented in the library itself?

**Comment by chintan9** [comment]
@lvndry use to v3 now

**Comment by chintan9** [comment]
@all-contributors please add @lvndry for Bug reports
