### ISSUE TITLE
Speed Popover goes out of screen

### ISSUE THREAD

**Issue by iamshouvikmitra** [chintan9/plyr-react#227]
**Describe the bug**
The popover that come when clicking on the setting icon in type: "audio", goes out of screen when placed at position that is close to the top of the screen.  
**To Reproduce**
1. Go to 'https://react-vfptdd.stackblitz.io/'
2. Click on 'Settings Icon'
3. Click on 'Speed'
4. See the options for selection goes out of the screen

**Expected behavior**
There should be a props for choosing the direction for the popover. Or the popover should have opened in downwards direction so that all options fit the screen

**Screenshots**
![Screenshot from 2020-05-31 18-44-04](https://user-images.githubusercontent.com/24479402/83353252-dbf1ac00-a36e-11ea-902d-e21c811454c0.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser : Chrome
 - Version 83.0.4103.61 (Official Build) (64-bit)

**Comment by iamshouvikmitra** [comment]
Any updates?

**Comment by iamshouvikmitra** [comment]
Hi @chintan9 ,
Could you guide me to correct place so that I can generate a PR?

**Comment by chintan9** [comment]
Hi @iamshouvikmitra 

Please fork my repo.  

Follow this https://github.com/chintan9/plyr-react#getting-started-for-development

Raise the PR for master .

You may use gitpod if you do not want to complicate your dev set up.  Just click on https://gitpod.io/#https://github.com/chintan9/plyr-react 
login with github and raise pr against master

**Comment by chintan9** [comment]
@all-contributors please add @iamshouvikmitra  for tests

**Comment by chintan9** [comment]
@all-contributors please add @iamshouvikmitra for User Testing and Bug reports

**Comment by chintan9** [comment]
@all-contributors please add @iamshouvikmitra for User Testing, tests and Bug reports
