### ISSUE TITLE
NextJS Global CSS

### ISSUE THREAD

**Issue by jonrrivera** [chintan9/plyr-react#275]
Unfortunately, this module cannot be integrated into next.js because it is importing Global CSS from within node_modules. NextJS require CSS declarations to happen in parent _app.js. 

Here is an [example](https://swiperjs.com/react/) of a react/NextJS integration that allows for individual CSS module declarations in _app.js. 

If we import PlyrComponent into a react component and follow this [example](https://stackblitz.com/edit/react-vfptdd?ctl=1&embed=1&file=index.js&hideExplorer=1&hideNavigation=1&view=preview) we end up getting this error:

<img width="1098" alt="Screen Shot 2020-07-29 at 11 19 05 AM" src="https://user-images.githubusercontent.com/18686388/88818960-55e6bb80-d18d-11ea-9106-a3e29ed6b97b.png">

Please let me know if you have any questions. Looking forward to helping with this one. 

Thank you!

**Comment by jonrrivera** [comment]
These links help as reference:

https://github.com/vercel/next.js/discussions/11664
https://github.com/vercel/next.js/blob/master/errors/css-npm.md

**Comment by chintan9** [comment]
I have working on convert this project to react hooks and typescript.

**Comment by jonrrivera** [comment]
Great, please let me know if you need any help.

**Comment by chintan9** [comment]
https://github.com/chintan9/plyr-react/tree/v3-master

Please review it

**Comment by iwatakeshi** [comment]
@jonrrivera I've just created a PR with some changes.

@chintan9 I'll need you to merge and publish an alpha version if possible. You can use a tool like [np](https://github.com/sindresorhus/np#readme) to create a release

**Comment by chintan9** [comment]
@jonrrivera  Can you retest it

**Comment by chintan9** [comment]
@all-contributors please add @jonrrivera for User Testing, Examples and Bug reports

**Comment by chintan9** [comment]
@all-contributors please add @iwatakeshi for Ideas & Planning, Answering Questions, Translation, User Testing, Examples and Bug reports

**Comment by chintan9** [comment]
@all-contributors please add @jonrrivera for User Testing, Examples and Bug reports
