### ISSUE TITLE
Convert to Typescript to aid intellisence and provide type support

### ISSUE THREAD

**Issue by calebdeji** [chintan9/plyr-react#308]
Development will be easy if we have our editors can provide IntelliSense. Type errors are easily encountered when  we input props without IntelliSense

Typescript provides types support which will actually provide IntelliSense during development and save us from unnecessary type error 

If this feature is welcomed, I can raise a PR for this issue. Thanks

**Comment by chintan9** [comment]
@calebdeji  use v3

**Comment by chintan9** [comment]
@all-contributors please add @iamshouvikmitra for Bug reports

**Comment by chintan9** [comment]
@all-contributors please add @calebdeji for Bug reports
