### ISSUE TITLE
Using ref-property

### ISSUE THREAD

**Issue by mnervik** [chintan9/plyr-react#339]
In my project I'm using `ref` to get the video-element, but that is no longer working as of *3.0.0*
Any chance of making it work again, or to make an alternative way to get the VideoElement-node?

**Comment by chintan9** [comment]
@mnervik  Can you share code or snippet of example?

**Comment by chintan9** [comment]
@all-contributors please add @mnervik for Bug reports

**Comment by chintan9** [comment]
@all-contributors please add @mnervik for Bug reports

**Comment by mnervik** [comment]
For testing I created a react app using the `create-react-app` boilerplate, and then imported `plyr-react` and created a new component named `VideoComponent`

```
import React from 'react'

import Plyr from 'plyr-react'
import 'plyr/dist/plyr.css'

function App() {
    return (
        <div className='App'>
            <VideoComponent />
        </div>
    )
}

export default App

class VideoComponent extends React.Component {
    componentDidMount() {
        this.ref = null
    }

    render() {
        console.log(this.ref)

        return (
            <div>
                <span>VideoPlayer</span>

                <Plyr
                    ref={(el) => (this.ref = el)}
                    source={{
                        type: 'video',
                        sources: [
                            {
                                src: 'http://clips.vorwaerts-gmbh.de/VfE_html5.mp4',
                            },
                        ],
                    }}
                />
            </div>
        )
    }
}
```

This code is working before updating to 3.x,x, but in the latest version it gives the warning *Function components cannot be given refs*, and tells me that my variable is `undefined`.

**Comment by iwatakeshi** [comment]
@mnervik I think I've got a fix for it. Try it out by changing your `package.json` to: 
```jsonc
{
  // ...
  "plyr-react": "git+https://github.com/chintan9/plyr-react.git#fix/forward-ref",
}
```
then run `npm update` or `yarn upgrade` (I think)

Let me know if it works.

**Comment by mnervik** [comment]
Yeah, it works

**Comment by chintan9** [comment]
@mnervik It is fixed v3.0.4

**Comment by mnervik** [comment]
Eh, apparently I't not quite that easy 😄
the ref does not seem to update when the video changes...In my case it always says 
```
<video class="plyr-react plyr" src="https://cdn.plyr.io/static/blank.mp4" controls></video>
```
and if you try to return the `.currentTime`-property, it always returns 0

## App.js
```import React, { Component } from 'react'
import Plyr from 'plyr-react'
import 'plyr/dist/plyr.css'

export default function App() {
    return <VideoPage />
}

class VideoPage extends Component {
    state = {
        loaded: true,
    }

    componentDidMount() {
        this.getData()

        setInterval(() => {
            if (this.player !== undefined) {
                console.log(this.player)
                console.log(this.player.currentTime)
            }
        }, 1000)
    }

    render() {
        return (
            <div>
                <h1>Video Page</h1>
                {this.state.loaded && (
                    <Plyr
                        ref={(player) => (this.player = player)}
                        options={{
                            ratio: '21:9',
                        }}
                        source={{
                            type: 'video',
                            sources: [
                                {
                                    src: `https://sample-videos.com/video312/mp4/720/big_buck_bunny_720p_1mb.mp4`,
                                    type: 'video/mp4',
                                },
                            ],
                        }}
                    />
                )}
            </div>
        )
    }

    getData() {
        this.setState({ loaded: true })
    }
}
```

**Comment by iwatakeshi** [comment]
@mnervik I didn't use `React.Component`, but I think is similar to what you are looking for and it works on my end:

```ts
export default function App() {
  const ref = useRef<HTMLPlyrVideoElement>()
  const [currentTime, setCurrentTime] = useState('0.00')
  const [id, setId] = useState<NodeJS.Timeout>()

  useEffect(() => {
    const onPlay: PlyrCallback = (event) => {

      setId(
        setInterval(() => {
          const currentTime = ref?.current?.plyr?.currentTime / 100

          setCurrentTime(currentTime.toFixed(2))
        }, 1000)
      )
    }

    const onPause: PlyrCallback = (event) => {
      clearInterval(id)
    }

    const onEnded: PlyrCallback = (event) => {
      clearInterval(id)
      setCurrentTime('0.00')
    }

    ref.current?.plyr?.on('play', onPlay)
    ref.current?.plyr?.on('pause', onPause)
    ref.current?.plyr?.on('ended', onEnded)

    return () => {}
  }, [])

  return <>
    <Plyr ref={ref} />
  <>
}
```

**Note**: I just added the types so they are not available yet.

**Comment by mnervik** [comment]
1. That seems awefully complicated compared to what I was using with the previous version

2. **One important note!**....Because of `setTimeout` & `setInterval` not always behaving as they should this might cause issues. By that I mean that if you start playing a video, and then switch to another browser tab, in modern browsers `setInterval` is given a lower priority and thus would probably just update once anywhere from a second to a minute (no way to know witch, and the time might between each update would probably change and not stay the same)...and that would cause the **currentTime**-value to get broken.

That second point is the main reason why this probably would not be the ideal situation. It just seems like a bunch of work to get a kind of ghetto solution of something that already worked in the previous version. Also, correct me if I'm wrong, but I think *useRef* is only for functional components, and there are not really any viable alternatives for classes.

To clarify that last point, this is all I needed before when creating an event for plyr
```
this.player.player.on('pause', () => { console.log(this.player.player.currentTime) })
```
Simple and easy to understand, and I don't have to code any logic to handle the properties from plyr, they are ready for use when you need them.

**Comment by iwatakeshi** [comment]
@mnervik If you're still using `fix/forward-ref` branch, try running the `update` command (or reinstall `node_modules`) and see if it's fixed now. Note that the property to access the `plyr` instance is `this.player.current.plyr`.

**Comment by mnervik** [comment]
That seems to work just fine

**Comment by chintan9** [comment]
@mnervik  Please use v3.0.5 

Thanks @iwatakeshi for fix
