### ISSUE TITLE
How to use player events like `onplay`

### ISSUE THREAD

**Issue by paschaldev** [chintan9/plyr-react#366]
Ref are not working properly with functional components and I can't figure out how to useplayer events. Any help would be appreciated

**To Reproduce**
```js
import React, { useRef } from 'react
const Video = () =>   {
  let player = useRef(null)
  ...
  return (
    <VideoPlayer
                source={{
                  type: 'video',
                  title: videoData.title,
                  sources: [
                    {
                      src: videoData.cloudfrontURL,
                      type: 'video/mp4',
                    }
                  ],
                  poster: defaultPoster,
                }}
                ref={player}
              />
  )
}
```

**Expected behavior**
I need to get the onplay events and get the current time of the video as well via the refs

**Comment by iwatakeshi** [comment]
@paschaldev Please see #339. There's a PR pending (#355) so once it's reviewed by @chintan9, he'll be able to publish it.

**Comment by chintan9** [comment]
@iwatakeshi  Release v3.0.4 with your change.
