### ISSUE TITLE
Crashes on re-rerender

### ISSUE THREAD

**Issue by paschaldev** [chintan9/plyr-react#376]
**Describe the bug**
When there is a state update in a component where the `Plyr` is, it crashes. 

**To Reproduce**
In a functional component with `plyr-react` already rendered, trigger a state change

```
Uncaught TypeError: can't access property "querySelectorAll", this.media is null
    getSources html5.js:14
    cancelRequests html5.js:125
    change source.js:32
    set plyr.js:840
    Plyr index.es.js:81
    React 6
    unstable_runWithPriority scheduler.development.js:653
    React 3
    workLoop scheduler.development.js:597
    flushWork scheduler.development.js:552
    performWorkUntilDeadline scheduler.development.js:164
    js scheduler.development.js:187
    js scheduler.development.js:857
    Webpack 20
```

**Expected behavior**
Player should be able to work during re-renders

**Screenshots**
![image](https://user-images.githubusercontent.com/13323281/95537354-6c0ec480-09e5-11eb-9284-fb5ee5bb0162.png)

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - Browser: Firefox (Developer Edition)
 - Version: 82.0b8 (64-bit)

**Additional context**
Tested on Create React App

**Comment by iwatakeshi** [comment]
@paschaldev Can you provide a repro? Either a repository or a [sandbox](https://codesandbox.io/index2) would be great. Thanks.

**Comment by chintan9** [comment]
https://github.com/chintan9/plyr-react/issues/378#issuecomment-710342253
Please try this solution @paschaldev
