### ISSUE TITLE
Crashes on component re render

### ISSUE THREAD

**Issue by DBankx** [chintan9/plyr-react#378]
The plyr functional component crashes on component unmounting and re mounting.
i have tried using the ref to try and access the destroy method, to destory the instance of the player, but it seems like the destroy method doesnt exist in your current application of plyr

**To Reproduce**
1. Add the plyr component
2. Try and re render the component... the player stops working

**Expected behavior**
Should work on re render, or should have a destory method i can access through the ref and destroy it using the useeffect hook

**Comment by chintan9** [comment]
@DBankx  Can share as codesandbox ?

**Comment by DBankx** [comment]
im currently busy so i will just copy and paste the code. sorry.
//
import React, {Fragment, useEffect, useRef} from "react";
import {observer} from "mobx-react-lite";
import {IClip} from "../../../infrastructure/models/clip";
import Plyr from "plyr-react";
import 'plyr-react/dist/plyr.css';

interface IProps{
    clip: IClip
}



const ClipPlayer: React.FC<IProps> = ({clip}) => {
    const ref = useRef<any>(null);
    
    
    
    useEffect(() => {
        console.log(ref.current != null && ref.current.plyr);
        return () => {
            ref.current != null && ref.current.destroy()
        }
    }, [])
    return (
        <Fragment>
        <div className={"p-mt-2"} >
            <Plyr 
                ref={ref}
                source={{type: "video", title: clip.title, sources: [
                    {
                        src: clip.url
                    }
                ]}}
            options={
                {
                    controls: ['play-large', 'play', 'progress', 'current-time', 'mute', 'volume', 'captions', 'settings', 'pip', 'airplay', 'fullscreen'],
                    settings: ['captions', 'quality', 'speed', 'loop'],
                    autoplay: true,
                    tooltips: {controls: true, seek: true}
                }
            }
            />
        </div>
        </Fragment>
    )
}

export default observer(ClipPlayer);

the player crashes when i rerender the component

**Comment by iwatakeshi** [comment]
@DBankx Try this branch out add see if this fixes your problem:

```
"plyr-react": "git+https://github.com/chintan9/plyr-react.git#fix/plyr-crash",
```

**Comment by chintan9** [comment]
@DBankx  Published v3.0.7 with fix. Please retest it

**Comment by FREEZX** [comment]
Not sure if i'm getting the same issue, but in my case, Plyr seems to restart playing if any redraw occurs. Not sure if i'm doing something wrong or if I missed an option.
[CodeSandbox here](https://codesandbox.io/s/react-colorful-demo-forked-ysq2h?file=/src/SlideControl.js). note that the video restarts every 6 seconds because i'm changing an unrelated state value.

**Comment by marcusstenbeck** [comment]
@FREEZX It's because you're creating a new options or settings object each frame. You can use `useMemo` too keep them stable.

```js
  const source = useMemo(
    () => ({ type: 'audio', sources: [{ src: audioUrl }] }),
    [audioUrl]
  );
  const options = useMemo(
    () => ({
      settings: ['loop'],
      displayDuration: true,
    }),
    []
  );

```

**Comment by iwatakeshi** [comment]
@FREEZX As pointed out by @marcusstenbeck, changing options will re-render the component
https://github.com/chintan9/plyr-react/blob/8d579121879dc3969e93b568c21e964e75153931/src/index.tsx#L41

If you believe `options` shouldn't be a dependency, feel free to create a PR.

**Comment by FREEZX** [comment]
I think the current behaviour is unintuitive, because even the given example usage is creating a new object and passing it directly:
https://github.com/chintan9/plyr-react#usage
Probably the best way to fix it would be to either:
- Check for deep equality and bail early if old and new options are equal
- Use plyr setters to change aspects of the player itself

**Comment by sloreti** [comment]
To add to @FREEZX's concerns, the [React docs](https://reactjs.org/docs/hooks-reference.html#usememo) say that,

> You may rely on useMemo as a performance optimization, not as a semantic guarantee. In the future, React may choose to “forget” some previously memoized values and recalculate them on next render, e.g. to free memory for offscreen components. Write your code so that it still works without useMemo — and then add it to optimize performance.

So in future version of React, even if you memoize the props being passed to the `Plyr` component, the video might restart when the parent component rerenders.

**Comment by timv88** [comment]
I also observed that when changing `options`/`settings` the component would crash on re-render. 

`useMemo` was not enough for my use case, so I am currently forcing a re-render using a `key` derived from the `controls` and `settings`.

```jsx
const reRenderKey = `${controls?.join('')}-${settings?.join('')}`

<Box key={reRenderKey}>
    <Plyr options={options} source={source} {...props} />
</Box>
```

**Comment by jenniferhail** [comment]
I had the same issue — my video component was redrawing while scrolling — but the `useMemo` fix worked!
