### ISSUE TITLE
React lazy css not showing

### ISSUE THREAD

**Issue by bbevren** [chintan9/plyr-react#401]
Hi, when component uses react lazy, plyr.css is not imported and plyr is not visible. 

//App.js router
import React ,{ lazy, Suspense } from 'react';
const Track = React.lazy(() => import('./Track'));

//Track.js
import { PlyrComponent } from 'plyr-react';

**Comment by iwatakeshi** [comment]
@bbevren Hi. Would you be able to provide a repro? It would speed things up for me. Thanks.
