### ISSUE TITLE
Support for captions via HTML <track> tag

### ISSUE THREAD

**Issue by joelsiks** [chintan9/plyr-react#428]
It'd be really nice to be able to pass in some captions option object with the caption url and language etc.

Something that would look like this: https://github.com/sampotts/plyr#html5-video

**Comment by chintan9** [comment]
@joelsiks  I was able pass use tracks using JS. 

demo:  https://react-1t11om.stackblitz.io/ 

code: https://stackblitz.com/edit/react-1t11om?file=src/App.js 

you can help me raise PR and I can look into that.

**Comment by amirHossein-Ebrahimi** [comment]
@joelsiks, you can add tracks array to  Plyr SourceInfo via props

e.g. 
```ts
const source = {
  // ...
 tracks: [
    {
      kind: "subtitles",
      label: "English",
      srcLang: "en",
      src: trackSrc,
      default: true
    }
  ]
}
  ```

Here is an example of [mdn \<track\> tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/track) video, integrated with `plyr-react`.

[![Edit on code sandbox](https://camo.githubusercontent.com/90808661433696bc57dce8d4ad732307b5cec6270e6b846f114dcd7ee7f9458a/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667)](https://codesandbox.io/s/pensive-shtern-pw3qu?file=/src/App.tsx)

**Comment by amirHossein-Ebrahimi** [comment]
Hi, @joelsiks did the mentioned answer solve the problem.

I know it is a react component it is better to get props for the track and embed the tracks to the source by ourselves.
Although it is absolutely possible, it is not the best match with the methodology we are following for integrations.
And It can also be done with a simple react wrapper component (react app is composed of components after all).

We would be happy to hear from developers like you, about what best suits your experience and workflows.
Here is an issue (#667) we are tracking toward the next major release of the package, any suggestions improving (`DX`) are appreciated.
