### ISSUE TITLE
Dynamically change source

### ISSUE THREAD

**Issue by CMella** [chintan9/plyr-react#447]
I don't think it's fair to call this a feature request because I'm sure there's a way to do this out of the box but I'd love it if this were clearer. 

What is the easiest way to change the content in the player? To give some context I'm trying to create a playlist functionality that will allow for a user to click from the menu and change the source of the video dynamically. 

I've tried using ref (ref.current.plyr.source = ...), I've tried using a function to disable the player, set the new content, and re-enable it, I've tried a bunch of stuff and nothing has worked.

Any suggestions?

**Comment by iwatakeshi** [comment]
@CMella Hi, this is an example to show how you can change it dynamically:

https://codesandbox.io/s/serene-darkness-el6rx?file=/src/App.tsx:791-809

Because it's on codesandbox, it may be a little quirky, but it did work for me when I refreshed the page.

**Comment by CMella** [comment]
@iwatakeshi I tried the solve you suggested and I'm having some trouble getting it to work.

See the code below:

`
import React, {useRef, useEffect, useState} from "react";
import Plyr from 'plyr-react'
import "plyr-react/dist/plyr.css";

export default function VideoPlayer(props) {

const {playlist, options} = props;
const [vidIndex, setIndex] = useState(0);
const sources = playlist.map(video => ({src:[video.video_id], provider: 'youtube' }));
const [source, setSource] = React.useState(sources[0]);

const ref = useRef()

React.useEffect(() => {
  const plyr = ref.current.plyr;
  setTimeout(() => {
    plyr.stop();
    setSource(vidIndex);
    plyr.play();
  }, 500);

}, [vidIndex]);


const videoList = playlist.map((vid, index) => 
    <li onClick={() => { setIndex(index)}}  className={`video ${vidIndex === index ? 'active' : ''}`}  key={index}>
      <div 
        className="hero"
        role="img"
        alt={vid.video_title}
        aria-label={vid.video_title}
        style={{backgroundImage: 'url(' + vid.video_thumbnail.url + ')'}}
      />
      <div className="video-desc">
            <h3 className="video-desc__now" >NOW PLAYING</h3>
            <p className="video-desc__title">{vid.video_title}</p>
            <h3 className="video-desc__play" >&#9654; PLAY NOW</h3>
      </div>
    </li>
)

  return (
    <div className={`player-container ${playlist.length > 1 ? 'multiple' : 'single'}`}>
        <Plyr options={options} ref={ref}  source={ { type: 'video', sources: [source], } } />
        {
          playlist.length > 1 ?
          <div className="right">
              <h2>Watch Now</h2>
              <ul> {videoList} </ul>
          </div>
          : null
        }
    </div>
  );

}
`

**Comment by CMella** [comment]
@iwatakeshi  Sorry for

**Comment by iwatakeshi** [comment]
@CMella I'm glad you figured it out. Here's a sample in case you want to use it as a reference:
https://codesandbox.io/s/serene-darkness-el6rx?file=/src/App.tsx
