### ISSUE TITLE
plyr setting control bug

### ISSUE THREAD

**Issue by Min5407** [chintan9/plyr-react#474]
**Describe the bug**
Hi,  I am trying to show quality in the setting control but for some reason it doesn't work in react plyr. It looks like it works in vanilla Js but in react it doesnt work. The default seems like it only shows the speed in the setting control so could you help me out on how to solve this issue. 

 <Plyr
          ref={videoRef}
          source={{
            type: 'video',
            title: '',
            sources: [
              {
                src: movUrl,
                type: 'video/mp4',
              },
            ],
          }}
          options={{
            settings: ['captions', 'quality', 'speed'],
            quality: {
              default: 576,
              options: [1080, 720, 576, 480, 360, 240],
            },
          }}
        />

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by iwatakeshi** [comment]
@Min5407 Would it be possible if you can create a sandbox to demonstrate the issue? From the top of my head, all settings are passed to Plyr so I'm not sure what the issue would be.

**Comment by amirHossein-Ebrahimi** [comment]
Thank you @Min5407 for your bug report
Could you please test the latest version and give us feedback about the issue you've faced

```bash
yarn add git://github.com/chintan9/plyr-react.git#package
```

**Comment by amirHossein-Ebrahimi** [comment]
‍‍‍the proposal is now ready
```bash
yarn add git://github.com/chintan9/plyr-react.git#release
```

feel free to reopen issue in a case it is still the case
