### ISSUE TITLE
YouTube videos are not played when initially clicking on the video container.

### ISSUE THREAD

**Issue by kestvir** [chintan9/plyr-react#502]
**Describe the bug**
When YouTube video is loaded, clicking the video container does not play the video. Only when the video is played using the plyr controls play button (in the bottom of the player) does the video start to get played and paused when the video container is clicked.

**To Reproduce**
Load a YouTube video and press on the container.

**Expected behavior**
The YouTube video should be played when users presses on the video container before playing the video with plyr controls.

**Desktop (please complete the following information):**
 - Browser: Chrome

**Comment by chintan9** [comment]
@kestvir  Can you create demo code over https://stackblitz.com/ ? 

That way we fix this issue faster?

**Comment by amirHossein-Ebrahimi** [comment]
Thank you @kestvir for your report, I assume this bug is fixed now but feel free to re-open the issue if it is still a problem with your project.

And in case you want to test the latest realise, you can test the latest version and give us feedback about the issue you've faced

```bash
yarn add git://github.com/chintan9/plyr-react.git#package
```
