### ISSUE TITLE
Scrolling produces redraw

### ISSUE THREAD

**Issue by mikestecker** [chintan9/plyr-react#510]
Just implemented into a new dev project which is a NextJS project, and I noticed that on page scroll, Plyr redraws the entire video object on scroll. If playing the video and you scroll. The video returns to the initial state.

UPDATE: I'm seeing the following error in my browser console: `The service worker navigation preload request was cancelled before 'preloadResponse' settled. If you intend to use 'preloadResponse', use waitUntil() or respondWith() to wait for the promise to settle.`

This is happening in both Chrome and Safari. I haven't tested other browsers.

**Comment by chintan9** [comment]
@mikestecker  Can you create demo code over https://stackblitz.com/ ?

That way we fix this issue faster?

**Comment by amirHossein-Ebrahimi** [comment]
Thank you @mikestecker for your bug report, I assume we might not have this bug anymore.
I'm going to close the issue feel free to re-open it and provide more information if it stills remains.

**Comment by baraglobal** [comment]
@mikestecker What was your fix for this in the end?
