### ISSUE TITLE
Volume and mute don't change when props are passed into the component.

### ISSUE THREAD

**Issue by kestvir** [chintan9/plyr-react#511]
**Describe the bug**
Volume and mute don't change when props are passed into the component.

**To Reproduce**
Pass the volume and muted props inside options prop.

**Expected behavior**
Video player should reflect the changes of the passed down props.

**Screenshots**
https://stackblitz.com/edit/react-sfov8t

**Desktop (please complete the following information):**
Browser: Chrome.

**Comment by amirHossein-Ebrahimi** [comment]
Hi @simon2004davies
Did you get time to test the latest version in your project, I'm existed to hear your feedback

**Comment by amirHossein-Ebrahimi** [comment]
‍‍‍the proposal is now ready
```bash
yarn add git://github.com/chintan9/plyr-react.git#release
```

feel free to reopen the issue in case it is still the case
