### ISSUE TITLE
Hls support

### ISSUE THREAD

**Issue by mnervik** [chintan9/plyr-react#525]
Is HLS not supported by this package?

It seems like the *blob*-data is not rendered when using hls.

**Comment by M2G** [comment]
Hi (for the author of the project), 

I have implemented HLS management in my project, you could be inspired if you wish : 

- https://github.com/M2G/react-plyr

Sincerely

**Comment by amirHossein-Ebrahimi** [comment]
HLS can also be supported via a wrapper component using `hls.js`

```tsx
import Plyr, { APITypes, PlyrProps, PlyrInstance } from "plyr-react";

const MyComponent = () => {
  const ref = useRef<APITypes>(null);
  useEffect(() => {
    const loadVideo = async () => {
      const video = document.getElementById("plyr") as HTMLVideoElement;
      var hls = new Hls();
      hls.loadSource("https://content.jwplatform.com/manifests/vM7nH0Kl.m3u8");
      hls.attachMedia(video);
      // @ts-ignore
      ref.current!.plyr.media = video;

      hls.on(Hls.Events.MANIFEST_PARSED, function () {
        (ref.current!.plyr as PlyrInstance).play();
      });
    };
    loadVideo();
  });

  return (
    <Plyr
      id="plyr"
      options={{ volume: 0.1 }}
      source={{} as PlyrProps["source"]}
      ref={ref}
    />
  );
};
```

Here is full example code sandbox example 

[![Edit on code sandbox](https://camo.githubusercontent.com/90808661433696bc57dce8d4ad732307b5cec6270e6b846f114dcd7ee7f9458a/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667)](https://codesandbox.io/s/hidden-frost-mpdjj?file=/src/HLS.tsx)

**Comment by amirHossein-Ebrahimi** [comment]
I'm going to close this issue since HSL support as a ready-to-use integration may not be the greatest option right now.

It would be beneficial if you could provide any more details.

**Comment by mnervik** [comment]
## More Details (written in JS, not TS)
### This code works in the previous version of plyr-react (2.2.1)
```
import { useRef, useEffect } from 'react'
import { PlyrComponent } from 'plyr-react'
import Hls from 'hls.js'

const App = () => {
	const ref = useRef()
	useEffect(() => {
		const video = ref.current.player.media

		const hls = new Hls()
		hls.loadSource('https://content.jwplatform.com/manifests/vM7nH0Kl.m3u8')
		hls.attachMedia(video)
	}, [])

	return <PlyrComponent ref={ref} />
}

export default App
```

### What I expected to be able to use in plyr-react (3.2.0)
- And yes, that example you used would work, but it's not really good practice to use document.getElementById inside react...
```import { useRef, useEffect } from 'react'
import PlyrComponent from 'plyr-react'
import 'plyr-react/dist/plyr.css'
import Hls from 'hls.js'

const App = () => {
	const ref = useRef()
	useEffect(() => {
		const video = ref.current.plyr.media
		const hls = new Hls()
		hls.loadSource('https://content.jwplatform.com/manifests/vM7nH0Kl.m3u8')
		hls.attachMedia(video)
	}, [])

	return <PlyrComponent ref={ref} />
}

export default App
```

**Comment by amirHossein-Ebrahimi** [comment]
Thank you @mnervik for your report, I will check it out soon and see the differences between these two versions.
