### ISSUE TITLE
Error with react router

### ISSUE THREAD

**Issue by SalaKrisztian** [chintan9/plyr-react#562]
**Describe the bug**
I get this issue when i'm switching the route.

Uncaught DOMException: Node.removeChild: The node to be removed is not a child of this node.
**To Reproduce**
1.Create a video component. The source can be anything, even youtube.
```
import { Component } from "react";
import Plyr from "plyr-react";
import 'plyr-react/dist/plyr.css';

export default class VideoPlayer extends Component {
    constructor(props: any) {
        super(props);
    }
    render() {
        return (
            <Plyr
                source={
                    {
                        type: 'video',
                        title: 'Test Video',
                        sources: [
                            {
                                src: 'http://localhost:5000/video',
                                type: 'video/mp4',
                                size: 1080,
                            }
                        ],
                    }
                }
            />
        );
    }
}
```
2.Add routing:
```
import React, { Component } from 'react';
import Header from './Header';
import Users from './Users';
import { NotFoundPage } from '../pages/NotFoundPage';
import VideoPlayer from './VideoPlayer';
import {
  BrowserRouter,
  Switch,
  Route,
  Link
} from "react-router-dom";

class App extends Component<any> {
  render() {
    return (
      <BrowserRouter>
      <Header></Header>   
        <Switch>
          <Route exact path="/" render={(props) => <Users />} />
          <Route path="/watch" component={VideoPlayer} />
          <Route path="*" component={NotFoundPage} />
        </Switch>
      </BrowserRouter>
    );
  }
}

export default App;
```
3. When going to an other route from localhost/videoplayer, i get the error described above and  everything freezes. I got the same issue with other react-plyr npm packages.

**Expected behavior**
Routing and video should work normally

**Comment by chintan9** [comment]
@SalaKrisztian Can you create sample at stackblitz.io ? That way we can see that issue.

**Comment by amirHossein-Ebrahimi** [comment]
Thank you @zenyr for your help, and thank you @SalaKrisztian for your feedback
could you test the latest version and give us feedback about the issue you've faced

could you please check the latest version from here and give us feedback?
```bash
yarn add git://github.com/chintan9/plyr-react.git#package
```

**Comment by Qiming-Liu** [comment]
https://github.com/chintan9/plyr-react/issues/562#issuecomment-906618738

I had this problem today, wrapping a `div` to the component solved it.
