### ISSUE TITLE
update ref binding and plyr construction

### ISSUE THREAD

**Issue by amirHossein-Ebrahimi** [chintan9/plyr-react#585]
Hi
First of all your typescript package ecosystem is really great and works perfectly with react.
But, the logic for instantiating PlyrJS and binding ref can be done with [react-aptor](https://github.com/amirHossein-Ebrahimi/react-aptor) behind the scene.

the package size is 351B and it also lets you have all API binding, deconstruction of the package (at clearing effects), ref binding, ... all with functional components out of the box.

In a case, you want precise documentation, it can be found over [here](https://ahimico.github.io/docs/react-aptor/tutorials-overview)

**Comment by chintan9** [comment]
@amirHossein-Ebrahimi  Can you create pr for me so we can look after that?

**Comment by amirHossein-Ebrahimi** [comment]
of course, I'll keep you updated.

**Comment by amirHossein-Ebrahimi** [comment]
First of all sorry for the delay, I was really working on my university projects

These are todos I can do but must check them out with you before coding

- [ ] Removing PropTypes usage in production 
> using typescript will suggest possible props and it can also be kept for the development process
- [ ] Remove default prop-types in production making and make code smaller
- [ ] restructure and separate types and react-aptor logics
- [ ] node-sass installation problem
> The project works fine without node-sass but here is the error I got while installation
```
npm ERR! code 127
npm ERR! path /home/<USERNAME>/Desktop/code/dev/plyr-react/node_modules/node-sass
npm ERR! command failed
npm ERR! command sh -c node scripts/install.js
npm ERR! sh: 1: node: not found

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/<USERNAME>/.npm/_logs/2021-08-10T12_40_50_084Z-debug.log
```
