### ISSUE TITLE
crashing when set options

### ISSUE THREAD

**Issue by sadeghi4j** [chintan9/plyr-react#605]
Hi,
Thank you for your component. 
setting options={{seekTime:2}} causes crash (all event listeners are called frequently)
How is it posible to change default value?
Thanks

**Comment by chintan9** [comment]
@sadeghi4j Can you create sample at stackblitz.io ? That way we can see that your example .

**Comment by amirHossein-Ebrahimi** [comment]
Thank you @sadeghi4j  for your report
Could you please test the latest version and give us feedback about the issue you've faced

```bash
yarn add git://github.com/chintan9/plyr-react.git#package
```
