### ISSUE TITLE
Subtitles not working

### ISSUE THREAD

**Issue by nachogonzalezqq** [chintan9/plyr-react#614]
**Describe the bug**
Subtitles are not being shown, and CC on/off button does nothing.

**To Reproduce**
Just include the following Plyr component:

<Plyr
            source={{
                type: 'video',
                title: 'example title',
                sources: [
                    {
                        src: 'http://content.bitsontherun.com/videos/3XnJSIm4-DZ7jSYgM.mp4',
                        type: 'video/mp4',
                        size: 720
                    }
                ],
                tracks: [
                    {
                        kind: 'captions',
                        label: 'Spanish',
                        srcLang: 'es',
                        src: '//playertest.longtailvideo.com/captions/sintel-sp.srt'
                    }
                ]
            }}
            />

**Expected behavior**
Subtitles should be visible.

**Comment by chintan9** [comment]
@nachogonzalezqq Can you create sample at stackblitz.io ? That way we can see that issue.

**Comment by nachogonzalezqq** [comment]
Hi @chintan9 ! Sorry for the delay. You can see a code example [here](https://stackblitz.com/edit/react-q97uow?file=src/App.js).

There you can see 2 different source objects. One of them gets the CC file from a remote source. That generates a CORS error (original plyr seems to have a way to configure cross-origin to allow this, it would be a nice feature!).

Second source object gets CC file from site root folder. That does not work either, not really sure why. 

Btw, is there any way to know when current video ended playing? I'm trying to do my own playlists implementation (to allow users to see following media and so) but I can't find a way to know when they finish their current video. 

Thanks in advance!

**Comment by chintan9** [comment]
https://react-gn25f3.stackblitz.io/

Use same domain will work well. 


```
Mixed Content: The page at 'https://react-gn25f3.stackblitz.io/' was loaded over HTTPS, but requested an insecure element 'http://content.bitsontherun.com/videos/3XnJSIm4-DZ7jSYgM.mp4'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html
```

```
Mixed Content: The page at 'https://react-gn25f3.stackblitz.io/' was loaded over HTTPS, but requested an insecure video 'http://content.bitsontherun.com/videos/3XnJSIm4-DZ7jSYgM.mp4'. This content should also be served over HTTPS.
```

**Comment by nachogonzalezqq** [comment]
Hi! But if I need to be able to load captions dinamically, with a backend that retrieves both an url to get the video as well as an url to get the captions, do I have to save those captions into public folder each time? We are serving everything over https

**Comment by nachogonzalezqq** [comment]
> Hi! But if I need to be able to load captions dinamically, with a backend that retrieves both an url to get the video as well as an url to get the captions, do I have to save those captions into public folder each time? We are serving everything over https

Well so I managed to figure this out. This is how my component looks like:

<Plyr source={mediaSource} crossOrigin="anonymus" />

Of course that mediaSource object is as showed in documentation, and it includes captions from a different domain. It works as expected on firsts tests, I'll re-open this incident if something comes up.

**Comment by andriken** [comment]
what about sizes, 720, 480 please help with that, I need It

**Comment by amirHossein-Ebrahimi** [comment]
Hey @andriken I didn't get your question well,

I guess these quality are supported could you take a look at our examples in dev branch for some examples.
If you can make a code-sandbox for future progress that would be appreciated.

**Comment by andriken** [comment]
Yea I checked the below stackblitz example In which It was present the code for quality, Thanks anyway.
