### ISSUE TITLE
How about keep state?

### ISSUE THREAD

**Issue by gamestap99** [chintan9/plyr-react#654]
i am using video in a tab. when chaning tab i lost video state. How about fix it?

**Comment by gamestap99** [comment]
Update issue when i changing a tab then the iframe be removed. then i turn back and i seen no iframe

**Comment by amirHossein-Ebrahimi** [comment]
Thank you @gamestap99 
Could you please test the latest version and give us feedback about the issue you've faced

```bash
yarn add git://github.com/chintan9/plyr-react.git#package
```

**Comment by gamestap99** [comment]
> Thank you @gamestap99 Could you please test the latest version and give us feedback about the issue you've faced
> 
> ```shell
> yarn add git://github.com/chintan9/plyr-react.git#package
> ```



> Thank you @gamestap99 Could you please test the latest version and give us feedback about the issue you've faced
> 
> ```shell
> yarn add git://github.com/chintan9/plyr-react.git#package
> ```
well, i will reply you soon
