### ISSUE TITLE
A few questions about  hls video example!

### ISSUE THREAD

**Issue by gamestap99** [chintan9/plyr-react#656]
Hi, I was readed your hls video example. I have a question about a line code this `ref.current!.plyr.media = video`. What do you do at this line?

**Comment by amirHossein-Ebrahimi** [comment]
Hi @gamestap99, I moved your question to the [discussion QA section](https://github.com/chintan9/plyr-react/discussions/658#discussion-3628467), I will also post the answer there too.

Issues seem to be stressful 😂, we try to keep it only for bugs and features 😉

**Comment by amirHossein-Ebrahimi** [comment]
Hi @gamestap99, I just mentioned that I wrongly suggest my post as an answer before getting your feedback, feel free to comment on that and submit that as an answer if it solves your problem.

**Comment by gamestap99** [comment]
> Hi @gamestap99, I just mentioned that I wrongly suggest my post as an answer before getting your feedback, feel free to comment on that and submit that as an answer if it solves your problem.

sorry, i reply you late. The answer of you resolved problem for me. Thank you very much!

**Comment by amirHossein-Ebrahimi** [comment]
That's totally fine, happy to hear that it solves your problem.
Feel free to [mark it](https://github.com/chintan9/plyr-react/discussions/658#discussioncomment-1485937) as an answer whenever you want.
