### ISSUE TITLE
Main challenges you have using plyr-react?

### ISSUE THREAD

**Issue by amirHossein-Ebrahimi** [chintan9/plyr-react#667]
We're planning to rewrite the documentation, which will save you a ton of time testing and let you move on to the task you want to do. To do so, we'll need to know the major problems you've encountered when using plyr-react.
You may also send us features that you're attempting to reproduce by integrating with other third-party packages.

_Originally posted by @amirHossein-Ebrahimi in https://github.com/chintan9/plyr-react/discussions/666_

**Comment by amirHossein-Ebrahimi** [comment]
Possibility to pass `plyr` default props Declaratively, same as react standards?
mentioned [here](https://github.com/chintan9/plyr-react/issues/685#issuecomment-970219208)

**Comment by Alken123** [comment]
Will you consider to be able to pass custom props for controls

**Comment by amirHossein-Ebrahimi** [comment]
> Will you consider an option for us to be able to pass custom props for controls

Hi @Alken123, Could you provide and example?
You can now pass both controls of `Plyr` initialization and direct props for `HTMLVideoElement`.

**Comment by Alken123** [comment]
@amirHossein-Ebrahimi Some thing like this controls: [ 'play-large', 'rewind', 'play', 'fast-forward', 'progress', 'current-time', 'duration', 'mute', 'volume', 'captions', 'settings', 'airplay', 'fullscreen', ]

**Comment by amirHossein-Ebrahimi** [comment]
Thank you @Alken123, sure we will consider being more declarative in props for the main next version!

**Comment by Alken123** [comment]
Yeah sure we'll wait

**Comment by amirHossein-Ebrahimi** [comment]
Hey @Alken123 
Just for sake of clarity, you want all tiny integration API to be mostly `flat`, `declarative`, and being at `Plyr convention`.

instead of configuring control in options (`options.control`) pass `control` props to pass and change it by yourself.

**Comment by Alken123** [comment]
> Hey @Alken123 Just for sake of clarity, you want all tiny integration API to be mostly `flat`, `declarative`, and being at `Plyr convention`.
> 
> instead of configuring control in options [(`options.control`) ](https://github.com/chintan9/plyr-react/blob/4644a4e21d67aea69e264da8cb77549f4c2213bb/src/index.tsx#L84-L95) pass `control` props to pass and change it by yourself.

Yeah i figured that out and was able to achieve it but do you know of any method that would help me with adding a string along with numerical value in the quality options like 1080p [English] or something of this sort.

**Comment by amirHossein-Ebrahimi** [comment]
‍‍‍the proposal is now ready
```bash
yarn add git://github.com/chintan9/plyr-react.git#release
```

Feel free to reopen the issue in case it is still the case
