### ISSUE TITLE
Server-Side Rendering Support

### ISSUE THREAD

**Issue by qinyiyao** [chintan9/plyr-react#668]
**Is your feature request related to a problem? Please describe.**

`ply-react` doesn’t really work with static site generators like Gatsby. It will produce the good ol’ “`document` is not defined” error.

**Describe the solution you'd like**

An out-of-the-box SSR implementation, or at least some documentation on workarounds.

**Describe alternatives you've considered**

I’ve been using `loadable-component` to circumvent this, but it no longer works in Gatsby v4.

**Comment by amirHossein-Ebrahimi** [comment]
Hi @qinyiyao 👋🏻 
Did you manage to fix the issue for your project, I'm existed to hear your feedback

**Comment by qinyiyao** [comment]
I ended up using React Suspense, which has no SSR support right now, but at least it works.

[Guide from Gatsby:](https://www.gatsbyjs.com/docs/using-client-side-only-packages/#workaround-4-use-reactlazy-and-suspense-on-client-side-only)

```js
import React from "react"

const ClientSideOnlyLazy = React.lazy(() =>
  import("../components/ClientSideOnly")
)
const MyPage = () => {
  const isSSR = typeof window === "undefined"

  return (
    <VideoContainer>
      {!isSSR && (
        <React.Suspense fallback={<div />}>
          <ClientSideOnlyLazy />
        </React.Suspense>
      )}
    </VideoContainer>
  )
}

//A wrapper holds the container in place to prevent layout shifting.
const VideoContainer = styled.div`
  aspect-ratio: 16 / 9;
`
```

**Comment by christophstockinger** [comment]
I running in the same issue with a custom SSR setup. Now I use React.lazy for the component and it works fine! This should be a good workaround!

**Comment by amirHossein-Ebrahimi** [comment]
Sorry for the delay, but we now pre-lease a new hook for our proposal method that helps you to be as low level as the child component (Plyr video), it helps create more custom components easily with `usePlyr` hook.

Feel free to add your custom component for SSR to our [example directory](https://github.com/chintan9/plyr-react/tree/dev/example) and help other users with your solutions. 🤗 
@qinyiyao @christophstockinger
