### ISSUE TITLE
SVG's not showing using React 17 from create-react-app

### ISSUE THREAD

**Issue by bradrice** [chintan9/plyr-react#683]
**Describe the bug**
I managed to get plyr-react to work in React 17, but for some reason the svg icons are not showing in any browser. I am getting the volume and progress bars. The buttons for the others are there, but transparent. i am using node-sass for my own style, but I have imported the plyr css like this:

import "plyr-react/dist/plyr.css";

**To Reproduce**
I'm using this code https://codesandbox.io/s/plyr-react-new-api-dpotl?file=/src/App.tsx

**Expected behavior**
Buttons should show

**Screenshots**
![image](https://user-images.githubusercontent.com/272352/141189054-e9cd2686-2ab8-4d8c-b80f-710deb6e5e00.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Chrome and Firefox
 - Version [e.g. 22] newest

**Comment by amirHossein-Ebrahimi** [comment]
Hey @bradrice, there is a closed [related issue](https://github.com/sampotts/plyr/issues/927) in plyr.
It seems the problem is with local storage, not react or CRA. Actually, the codesandbox you mentioned itself uses react 17 and create react app.


**Solution** mentioned [here](https://github.com/sampotts/plyr/issues/927#issuecomment-395930523)
> - Check local storage has a sprite and it if does load from there
> - Make the XHR request
> - Update local storage for next page view as well as update sprite in DOM

**Comment by bradrice** [comment]
Thanks for your help. If I look in LocalStorage using devtools I don't see a sprite. Shouldn't plyr be taking care of loading the sprite? Are you saying I have to make my own request to get the svg?

**Comment by amirHossein-Ebrahimi** [comment]
If you don't block storage access to javascript and you can set your own data in local storage e.g. `window.localStorage('key', 'value')`, I guess you might need this extra fetch on your own. 

But in a case, you need this request, your local-storage is something like this:

```js
fetch('https://cdn.plyr.io/3.6.8/plyr.svg')
  .then(res => res.text())
  .then(content => {
    window.localStorage('cache-sprite-plyr', JSON.stringify({content}))
   })
```
- you might need extra re-render for plyr to work
- you might need to fix content string (I'm not confident it will work)


Let us know if that helped you

**Comment by bradrice** [comment]
Thanks. I did manage to copy the sprite over from the nodeModules and import it into iconUrl. I'll try your method as well and use the best. Thanks so much.
