### ISSUE TITLE
Build error with plyr.css

### ISSUE THREAD

**Issue by bradrice** [chintan9/plyr-react#684]
**Describe the bug**
./node_modules/plyr-react/dist/plyr.css
ParserError: Syntax Error at line: 1, column 51

**To Reproduce**
npm run build

**Expected behavior**
A build without error

**Screenshots**

**Desktop (please complete the following information):**
 Running WSL in Windows 10

**Comment by amirHossein-Ebrahimi** [comment]
Hey @bradrice, Check out this issue [#628](https://github.com/chintan9/plyr-react/issues/628) ley me know if that fixed your error or not

**Comment by bradrice** [comment]
Well, that got me close. I had to do extra steps. I followed the steps of unminifying the plyr.css and then I had to put it into sassmeister to compile it into css. Then I copied the css into the css validator and found errors. I fixed those. However, I couldn't put it in my project as a scss file, but I had to create a new plyr.css file and import it.

I'm wondering if you could include your css source file or scss in your project so it doesn't have to be run through the unminifier.

**Comment by amirHossein-Ebrahimi** [comment]
Actually, we are trying to make these two packages as decoupled as possible.
It might be needed to install `plyr` as `peerdependencies` in a future update, then it is going to be handled normally via package management and bundling process. but thanks for your feedback, and don't hesitate to post any issue (including your CSS issue) [here (#667)](https://github.com/chintan9/plyr-react/issues/667)
