### ISSUE TITLE
Poster option not working

### ISSUE THREAD

**Issue by bradrice** [chintan9/plyr-react#685]
**Describe the bug**
I can't seem to get my player to use a poster if I add it as an option to my  plyr-react options.

**To Reproduce**
1. import poster from "../../assets/images/TUposter.svg";
2. const videoOptions = {
    controls: ['rewind','play-large', 'play', 'fast-forward', 'progress', 'current-time', 'mute', 'volume', 'fullscreen', ],
    loadSprite: true,
    iconUrl: sprite,
    poster: poster
    }

**Expected behavior**
The image should appear as a poster before the user clicks play

**Screenshots**

**Desktop (please complete the following information):**
Windows WSL Linux 4.4.0-19041-Microsoft

**Additional context**
I've tried .png as well as .svg

**Comment by amirHossein-Ebrahimi** [comment]
Hey @bradrice, could you provide a code sandbox make it online available to test the issue?

**Comment by bradrice** [comment]
Well, I seem to be having config issues with the SCSS in my sandbox.

https://codesandbox.io/s/falling-frost-2tnz2?file=/src/plyrcomponent.tsx

I'm not actually using Plyr sass, so I don't know why the error.

**Comment by amirHossein-Ebrahimi** [comment]
@bradrice, your code-sandbox seems to be off-version (not containing the latest changes and file content).

If you think the issue comes from the SCSS world, Could you try to replicate the same action and style that `plyr` gives to the poster when the source is provided by `youtube` or `vimeo` in your style and configuration?

**Comment by flyingwip** [comment]
Hi ,

I am having the same issue. The setup I use is quite default. 

const videoSrc = {
            type: "video",
            sources: [
                {
                    src: "https://cdn.plyr.io/static/demo/View_From_A_Blue_Moon_Trailer-576p.mp4",
                    poster: 'https://cdn.plyr.io/static/demo/View_From_A_Blue_Moon_Trailer-HD.jpg'
                }
              ]
            }

<Plyr source={videoSrc} ></Plyr>

Having said that. None of the options I add do not work. The video player works.

I notice in the generated HTML i do not see the 
<div tabindex="0" class="plyr plyr--full-ui plyr--video plyr--html5 plyr--fullscreen-enabled plyr--paused plyr--stopped plyr--pip-supported plyr--captions-active plyr--captions-enabled **plyr__poster-enabled**">

All the options added in react source are generated in the source tag

<source src="https://cdn.plyr.io/static/demo/View_From_A_Blue_Moon_Trailer-576p.mp4" poster="https://cdn.plyr.io/static/demo/View_From_A_Blue_Moon_Trailer-HD.jpg">

**Comment by amirHossein-Ebrahimi** [comment]
Hey @flyingwip, I tested your code and it worked, It took quite a long to load by plyr added the `data-poster` to HTML tag and it worked.

the `sources` item doesn't get the poster, and the video source does.
```js
  source={{
        type: "video",
        // add poster directly to source config here
        poster: "https://peach.blender.org/wp-content/uploads/title_anouncement.jpg?x11217",
        sources: [
          {
            src: "https://cdn.plyr.io/static/demo/View_From_A_Blue_Moon_Trailer-576p.mp4",
            type: "video/mp4"
          }
        ]
      }}
```
 
Take a look at [complete codesandbox](https://codesandbox.io/s/plyr-react-new-api-forked-3rx3w?file=/src/App.tsx:145-479) 


I guess it must be possible to pass the `poster` (or at least `data-poster`)  directly through react component `<Plyr poster="something"/>`, but unfortunately, they are not supported yet. 

Make sure to add your feature request in [#667](https://github.com/chintan9/plyr-react/issues/667) and [discussions](https://github.com/chintan9/plyr-react/discussions) they will be implemented if they become popular :)

**Comment by bradrice** [comment]
I finally got a basic codesandbox.io showing poster not working:

https://codesandbox.io/s/plyr-react-poster-2tnz2?file=/src/plyrcomponent.tsx:535-566

**Comment by amirHossein-Ebrahimi** [comment]
> I finally got a basic codesandbox.io showing poster not working:
> 
> https://codesandbox.io/s/plyr-react-poster-2tnz2?file=/src/plyrcomponent.tsx:535-566

Poster is part of source object not options object, search for " poster: '/path/to/poster.jpg'," in plyr [documentation](https://github.com/sampotts/plyr).
```jsx
 const vidSrc: iVideoSource = {
    type: "video",
    // @ts-ignore
    poster: poster,
    sources: [
      {
        src: videoId,
        provider: "html5",
        size: 720
      }
    ]
  };
  ```

Unfortunately, typescript will complain about that, but it will be fixed on the following releases of `plyr-react`.

**Comment by amirHossein-Ebrahimi** [comment]
Hey, @bradrice and @flyingwip I'm going to close this issue but feel free to re-open it if you faced any other issues.

**Comment by flyingwip** [comment]
Tanx! Obvouslly I did not read well. I got it working. Again thank you
