### ISSUE TITLE
Settings in options won't work

### ISSUE THREAD

**Issue by pooryak** [chintan9/plyr-react#687]
Hi
As you can see in below link, I added a quality option but it won't appear on the screen
https://codesandbox.io/s/plyr-js-example-with-react-forked-6luq2?file=/pages/index.js

**Comment by amirHossein-Ebrahimi** [comment]
Hi @pooryak, It seems that Plyr itself have a request feature [#1741](https://github.com/sampotts/plyr/issues/1741) for HSL quality switch, it has been reported in other issues e.g. [#1919](https://github.com/sampotts/plyr/issues/1919)
and discussed in details in [this comment](https://github.com/sampotts/plyr/issues/652#issuecomment-445457542).
By the way it seems that it works in vanilla js approach, here is [codepen example](https://codepen.io/datlife/pen/dyGoEXo?editors=0010)

By the way, we might consider make a ready to use Hls player.
The problem with out code is that hls doesn't trigger `Hls.Events.MANIFEST_PARSED` event,

I updated the [codesandbox](https://codesandbox.io/s/plyr-js-example-with-react-forked-hoeqm?file=/pages/index.js) so you can take a look and investigate more, see if you can fix the issue.
I might work more on hls player in the the weekend considering this issue to.
let me know if you can fix it.

**Comment by pooryak** [comment]
`import { useEffect, useRef } from 'react';

import 'plyr/dist/plyr.css';
import Hls from 'hls.js';
// import Plyr from "plyr-react";
import PlyrJS from 'plyr';


const MyComponent = (data) => {
  const innerRef = useRef(null);
  const hls = useRef(new Hls());
  const videoOptions = {
    ...(ad
      ? {
          ads: {
            enabled: true,
            publisherId: 'sd',
            tagUrl: ads,
          },
        }
      : null),
  };
  const createPlayer = () => {
    // eslint-disable-next-line no-unused-vars
    const plyrPlayer = new PlyrJS('#plyr', videoOptions);
  };
  hls.current.on(Hls.Events.MANIFEST_LOADED, () => {
    videoOptions.quality = {
      default: hls.current.levels[hls.current.levels.length - 1].height,
      options: hls.current.levels.map((level) => level.height),
      forced: true,
      // Manage quality changes
      onChange: (quality) => {
        hls.current.levels.forEach((level, levelIndex) => {
          if (level.height === quality) {
            hls.current.currentLevel = levelIndex;
          }
        });
      },
    };

    createPlayer();
  });
  useEffect(() => {
    if (!innerRef.current) return;

    if (data.data.arvan_hls && Hls.isSupported()) {
      hls.current.loadSource(data.data.arvan_hls);
      hls.current.attachMedia(innerRef.current);
    } else {
      createPlayer();
    }

    if (innerRef.current?.plyr) {
      innerRef.current.plyr.source = data.arvan_hls;
    }
    innerRef?.current.plyr?.on('play', () => hls.current.startLoad());

    innerRef?.current.plyr?.on('qualitychange', () => {
      if (innerRef.current?.plyr?.currentTime !== 0) {
        hls.current.startLoad();
      }
    });
    return () => {
      innerRef.current.plyr.destroy();
    };
  }, [videoOptions]);

  return (
    // eslint-disable-next-line jsx-a11y/media-has-caption
    <video id="plyr" options={videoOptions} source={null} ref={innerRef}>
    </video>
  );
};

export default MyComponent;
`
It worked
But I have an unusual error at console
everything work as expected on the desktop but when I see it on mobile 
`Access to XMLHttpRequest at 'https://napi.arvancloud.com/vod/channels/c49885f0-11e3-4f15-b0a4-68392958643b/ads' from origin 'http://imasdk.googleapis.com' has been blocked by CORS policy: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.
VM7:1 GET https://napi.arvancloud.com/vod/channels/c49885f0-11e3-4f15-b0a4-68392958643b/ads net::ERR_FAILED 200
%D8%AA%D8%B3%D8%AA:1 GET blob:http://localhost:3000/07d8442b-f441-4016-8362-f64cc9775bd0 net::ERR_FILE_NOT_FOUND`
I get that cors error on desktop but it works anyway.
when I disable ads it works on mobile too.

**Comment by amirHossein-Ebrahimi** [comment]
Plyr has partnered up with [vi.ai](https://vi.ai/publisher-video-monetization/?aid=plyrio) to offer monetization options for your videos.
Here are two things that might be helpful
1. Add cross origin attribute to Plyr component (native video element)
2. Update your Arvan API channel to accept requests from origin 'http://imasdk.googleapis.com'

**Comment by pooryak** [comment]
I changed my ads from arvan to a sample from google I faced the same error again.
firefox shows this one: Security Error: Content at http://localhost:3000/post/202111161/%D8%AA%D8%B3%D8%AA may not load data from blob:http://localhost:3000/297f0ec5-faf5-46fc-87e7-6f028e1a6f94.
by the way, it shows this error on desktop too but it works on it anyway

**Comment by amirHossein-Ebrahimi** [comment]
Could you test your ads player with [vi.ai](https://www.vi.ai/publisher-contextual-video/?aid=plyrio)?
Did you test the code in other browsers e.g. chrome?

**Comment by pooryak** [comment]
yes
Yes, I did, both in chrome and firefox

**Comment by amirHossein-Ebrahimi** [comment]
did it face the same issue with vi.ai?
Make sure you don't have an ad blocker, you can also check out the [following](https://support.mozilla.org/en-US/questions/1279624)
. it may help

**Comment by Shohzodt** [comment]
Hey, i used all from codesandbox but It is not rendering qualities(

**Comment by amirHossein-Ebrahimi** [comment]
Could anyone solve this problem, 
We published a proposed version that helps you to be as low level as the child component, it helps create more custom components easily with `usePlyr` hook.
feel free to add your custom component to our [example directory
](https://github.com/chintan9/plyr-react/tree/dev/example)
