### ISSUE TITLE
3.2.0 causing videos to disappear

### ISSUE THREAD

**Issue by matthewlein** [chintan9/plyr-react#689]
**Describe the bug**
After updating from 3.1.0 to 3.2.0, some pages show a flicker of video then disappears completely, showing blank. No controls, nothing rendered at all.

the rendered html looks like the plyr was not instantiated at all:

```
<video class="plyr-react plyr"></video>
```

No errors logged, no warnings

Downgrading to 3.1.0 fixes completely.

**To Reproduce**
I have not figured out why this happens only on some pages. The react-plyr component is being loaded through `@loadable/component` and is server side rendered. The same loaded component works fine on other places. Different video sources also disappear. Removing the  `@loadable/component` and importing directly made no difference. 

**Desktop (please complete the following information):**
 - OS: macOS
 - All browsers

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - Browser: safari

**Comment by amirHossein-Ebrahimi** [comment]
Hi @matthewlein , could you test the latest unofficial version and see what happens, there is an internal issue with plyr not respecting the latest updated dom. it is fixed in the following version
```
yarn add git://github.com/chintan9/plyr-react.git#package
```

**Comment by matthewlein** [comment]
Installing that version seems to work fine at first look.

**Comment by amirHossein-Ebrahimi** [comment]
could we please, publish the latest master version @chintan9. It seems to work fine every where 😍

**Comment by chintan9** [comment]
I will do that tomorrow

**Comment by chintan9** [comment]
@matthewlein & @matthewlein  v3.2.1 published. 

Please test now.
