### ISSUE TITLE
New logo for the main page

### ISSUE THREAD

**Issue by amirHossein-Ebrahimi** [chintan9/plyr-react#690]
What do you think about the new logo?
Feel free to post your criticisms...
![plyr-react-logo](https://user-images.githubusercontent.com/23579958/142599249-0c2d350c-92dc-409c-8585-742a9467d36b.png)

**Comment by chintan9** [comment]
Which font we are using ? 
Can we use Inter fonts ? 

https://rsms.me/inter/

**Comment by amirHossein-Ebrahimi** [comment]
I used Plyr font ([Gordita](https://www.cufonfonts.com/font/gordita))
Sure I will check that out

**Comment by amirHossein-Ebrahimi** [comment]
![plyr-react-logo--inter](https://user-images.githubusercontent.com/23579958/142738113-9ec53552-6770-4634-be6f-cf4b86aae410.png)
