### ISSUE TITLE
Codesandbox.io example not working in Chrome

### ISSUE THREAD

**Issue by bradrice** [chintan9/plyr-react#698]
**Describe the bug**
The codesandbox.io for typescript example isn't working in Chrome with 3.2.1

**To Reproduce**
1. Open this link in Chrome: https://codesandbox.io/s/plyr-react-new-api-forked-cg08k?file=/src/App.tsx
2. Click play

**Expected behavior**
When clicking play, the video should play, but it is not.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version  96.0.4664.45 (Official Build) (64-bit)
 - 
**Additional context**
I'm trying to figure out how to call the plyr methods from outside the player and discovered they aren't working in chrome. It appears to wok ok in Firefox.

**Comment by chintan9** [comment]
there seems issue with chrome I guess. it always works for me in new tab
https://cg08k.csb.app/

**Comment by amirHossein-Ebrahimi** [comment]
I'm going to close this issue, feel free to add your solution in case you solved it
