### ISSUE TITLE
options not working with youtube video

### ISSUE THREAD

**Issue by deepa-wisetr** [chintan9/plyr-react#712]
**Describe the bug**
volumne and mute options not working for youtube and viemo 

**To Reproduce**
https://codesandbox.io/s/plyr-react-new-api-forked-uczso?file=/src/App.tsx

**Expected behavior**
[Normal video.](https://codesandbox.io/s/plyr-react-poster-2tnz2?file=/src/plyrcomponent.tsx:535-566)

**Screenshots**
![image](https://user-images.githubusercontent.com/83942092/145204220-a3346928-6ca1-442f-bb4c-936e0b556852.png)

**Comment by amirHossein-Ebrahimi** [comment]
Hey @deepa-wisetr 

It seems for better user experience plyr saves all options presets in your localStorage
And it will sure work for first user view

but if you want to set the muted and volume every time you can do it yourself.

```js
 // the following line will output different base on what you have changed to plyr player 
  console.log(window.localStorage.getItem('plyr')) // {"muted":false,"volume":0.3} 
// reset the player localstorage to new the thing we want
  window.localStorage.setItem('plyr', JSON.stringify(videoOptions))
```

if you think adding something like `resetPlyrStorageOnMount` will be helpful please add it to [here](https://github.com/chintan9/plyr-react/issues/667) so people can discuss more about it.

**Comment by amirHossein-Ebrahimi** [comment]
Also, upvote for [this issue](https://github.com/sampotts/plyr/issues/532),  and feel free to close the issue if it solves the problem
