### ISSUE TITLE
Missing fullscreen control in YOUTUBE provider

### ISSUE THREAD

**Issue by MasterProvider** [chintan9/plyr-react#715]
**Describe the bug**
The fullscreen button is missing in YouTube source as a provider

```jsx
<Plyr
      options={{
        quality: {
          default: 576,
          options: [4320, 2880, 2160, 1440, 1080, 720, 576, 480, 360, 240]
        },
        controls:['play-large', 'play', 'progress', 'current-time', 'mute', 'volume', 'captions', 'settings', 'pip', 'airplay', 'fullscreen'],
        settings: ["captions", "quality", "speed", "loop"]
      }}
      source={{
        type: "youtube",
        sources: [
          {
            src: "TmWIrBPE6Bc",
            provider: "youtube"
          }
        ]
      }}
    />
```

**Expected behavior**
Also, YouTube has a small screen behavior instead of fitting it as a default screen of youtube

**Screenshots**
![Screenshot (718)](https://user-images.githubusercontent.com/48547307/146048747-74055013-ce26-4a96-aaf4-da4cd9b0f817.png)

**Desktop (please complete the following information):**
 - Device: HP
 - OS: Windows 10
 - Browser [Chrome,Firefox]

**Additional context**

**Comment by amirHossein-Ebrahimi** [comment]
Hey @MasterProvider, could you fill in information about the device you are testing on.
Could you check functionality on [main example](https://codesandbox.io/s/plyr-react-new-api-forked-cg08k?file=/src/App.tsx)?

**Comment by MasterProvider** [comment]
Thank you @amirHossein-Ebrahimi now I got it, I changed the source type as a video instead of youtube

**Comment by MasterProvider** [comment]
now it works like a charm 

<Plyr
      options={{
        quality: {
          default: 576,
          options: [4320, 2880, 2160, 1440, 1080, 720, 576, 480, 360, 240]
        },
        controls:['play-large', 'play', 'progress', 'current-time', 'mute', 'volume', 'captions', 'settings', 'pip', 'airplay', 'fullscreen'],
        settings: ["captions", "quality", "speed", "loop"]
      }}
      source={{
        type: "video",
        sources: [
          {
            src: "TmWIrBPE6Bc",
            provider: "youtube"
          }
        ]
      }}
    />
