### ISSUE TITLE
Setting Width and Height of Player

### ISSUE THREAD

**Issue by hashweather** [chintan9/plyr-react#716]
I wish to set the width and height of the window. The reason been I am loading the page into an iframe so I want the video to fit the dimensions of the iframe. How can I achieve that with Plyr.

Below is my code:
```
    const [width, setWidth] = useState('100vw');
    const [height, setHeight] = useState('100vh');

    useEffect(() => {
        setWidth(window.innerWidth);
        setHeight(window.innerHeight);
    }, []);

    const videoSrc = {
        type: "video",
        sources: [
            {
                src: videoUrl,
            }
        ]
    };

    return (
        <section
            style={{
                transition: 'all .2s',
                background: 'black',
                width: width,
                height: height,
                position: 'relative'
            }}
        >
         <Plyr
                    source={videoSrc}
                    options={{
                        hideControls: true,
                        ratio: '16:8'
                    }}
                    width={width} //This seems not to be working in an iframe
                    height={height} //This seems not to be working in an iframe
                />
</section>
```

When I load the page with an iframe the video is not displaying with the dimensions of the iframe. The video is always stucked at the top. 

How can I prevent that. I want the video to take the size of the iframe and the controls should always be at the bottom of the iframe just like YouTube embed.

How can I achieve that?

Thank you

**Comment by amirHossein-Ebrahimi** [comment]
Hey @hashweather, Cause your problem seems to be more related to UI, could you please provide a [codesandbox](https://codesandbox.io/) representation of your issue?

**Comment by hashweather** [comment]
Hello @amirHossein-Ebrahimi  Thanks for responding. But before the Codesandbox I just want to confirm, how can I set with and height of the Player? Is this way correct?

              <Plyr
                    source={videoSrc}
                    options={{
                        hideControls: true,
                        ratio: '16:8'
                    }}
                    width={200}  //Seems not to be working
                    height={200} //Seems not to be working 
                />
Even setting the width and height through the `style `attribute seems not the working

**Comment by amirHossein-Ebrahimi** [comment]
Hi @hashweather, all props you pass will directly pass to the inner video element, but plyr will re-organize the dom in its initialization, I'm afraid that it can be handled via props.

you can set the it inside CSS for all instance like
```css
.plyr {
  width: 200px;
  height: 200px;
}
```

or wrap the `<Plyr />` instance inside a wrapper e.g. div  and set your limits over there

```jsx
 <div style={{ width:200, height: 200 }}>
        <Plyr  {...plyrProps}  />
 </div>
```

**Comment by amirHossein-Ebrahimi** [comment]
feel free to ask for clearing any ambiguity or closing the issue if the answer solved that 🤗
