### ISSUE TITLE
CustomPlyrInstance props

### ISSUE THREAD

**Issue by bradrice** [chintan9/plyr-react#729]
Using the new CustomPlyrInstance example works great. 

How can I use it with props for source and options? I see you set source at the top of the file outside of the component. If I used this code in my Tooling U player, could I wrap it in a component that accepts props from the outside?

**Comment by amirHossein-Ebrahimi** [comment]
Hey @bradrice, happy to hear it works as expected.
Yeah, It is totally okay to pass the props as normal (in term of dynamism).

But remember passing the new `options` or  `source` will component to do all react life cycle again and re-instantiate the `plyr` which is 99% the things you actually wants. but in a case you face some problem keep in mind the mentioned things can be solve with memoization. [see the dependency array](https://github.com/chintan9/plyr-react/blob/ef73315f7fb414db39f1fe5ebba88561b14da24a/src/index.tsx#L73)

you can also pass event handler as props and make your component more reusable.

```tsx
  <CustomPlyrInstance
          ref={ref}
          source={videoSource}
          options={videoOptions}
          onEnded={() => console.log("I'm Ended")}
          onCanPlay={(api) => {
             // pass api directly in CustomPlyrInstance as the function arguements
             api.plyr.play()
             console.log('duration of audio is', api.plyr.duration)
             // you can also reference the `ref` here e.g. `ref.current.plyr.fullscreen.enter()`
         }}
   />
```

**Comment by bradrice** [comment]
If I want to use it as is, what do I need to install in my project. I already have the current plyr-react installed. Do I need to add anything?

**Comment by amirHossein-Ebrahimi** [comment]
```bash
yarn remove plyr-react
# Then install the new one
yarn add git://github.com/chintan9/plyr-react.git#release
```
It should update your `package.json` to something like this
```json
  "dependencies": {
    "plyr-react": "git://github.com/chintan9/plyr-react.git#release"
  }
```

**Comment by amirHossein-Ebrahimi** [comment]
@chintan9 could you please make a mechanism and standardization for the alpha release system, you mentioned in [this comment](https://github.com/chintan9/plyr-react/issues/649#issuecomment-941269656). I guess we have so many unused branches and if we don't organize them it will soon chaos.

The are two branches that I maid for beta testing purposes one is `#package` which is now merged in master and one is `#release` branch which we should wait for more feedback from @bradrice.

**Comment by chintan9** [comment]
I will do that by end of week.

**Comment by amirHossein-Ebrahimi** [comment]
Thanks, @chintan9.

I'm not sure I get the whole idea well, but in a case, I get that right, you mean getting a branch from the latest `#developer` branch means we are going to release an alpha version of `plyr-react`. Is this correct?

In the case of releasing just consider we are going to use GitHub as a semi npm registry so it will download all project files from the HEAD of the branch, we are targeting.
In case of solving this issue, I did it on my own and removed all nonrelated things even "devDependcies" from `package.json`
I it can be solved well with strategies like the one [uWebSockets.js](https://github.com/uNetworking/uWebSockets.js#package-easily-installed) uses as its main release mechanims.

**Comment by bradrice** [comment]
I did install from git
yarn add git://github.com/chintan9/plyr-react.git#release
 and I'm getting:

Can't resolve 'plyr-react/dist/plyr.css'

**Comment by bradrice** [comment]
How do I change the source?

I can't figure out where in the code to change the source to override the defaultProps. I have the current audio src in Redux store, but can't seem to override it in the new code.

Plyr.defaultProps = {
  options: {
    controls: [
      "rewind",
      "play",
      "fast-forward",
      "progress",
      "current-time",
      "duration",
      "mute",
      "volume",
      "settings",
      "fullscreen",
    ],
    i18n: {
      restart: "Restart",
      rewind: "Rewind {seektime}s",
      play: "Play",
      pause: "Pause",
      fastForward: "Forward {seektime}s",
      seek: "Seek",
      seekLabel: "{currentTime} of {duration}",
      played: "Played",
      buffered: "Buffered",
      currentTime: "Current time",
      duration: "Duration",
      volume: "Volume",
      mute: "Mute",
      unmute: "Unmute",
      enableCaptions: "Enable captions",
      disableCaptions: "Disable captions",
      download: "Download",
      enterFullscreen: "Enter fullscreen",
      exitFullscreen: "Exit fullscreen",
      frameTitle: "Player for {title}",
      captions: "Captions",
      settings: "Settings",
      menuBack: "Go back to previous menu",
      speed: "Speed",
      normal: "Normal",
      quality: "Quality",
      loop: "Loop",
    },
  },
  source: {
    type: "audio",
    sources: [
      {
        src: "",
        type: "audio/mp3",
      },
    ],
  },
};

**Comment by bradrice** [comment]
For some reaon my getApi is getting called twice, so adding eventListeners in there is adding two of each listeners.

```
const getAPI = (plyr: PlyrJS | null) => {
  if (!plyr)
    return () =>
      new Proxy(
        { plyr: { source: null } },
        {
          get: (target, prop) => {
            if (prop === "plyr") {
              return target[prop];
            }
            return noop;
          },
        }
      );
  console.log("in getApi");
  plyr.on("ended", onEndedPlay);
  plyr.on("canplay", onCanPlay);


  return () => ({
    /**
     * Plyr instance with all of its functionality
     */
    plyr,
  });
};
```
Is this the proper place to add event listeners?

Also, this does not work:

```
plyr.addEventListener('canplay', ()=> {
console.log("ready to play");
});
```
It appears I need the element to add the event listener that way and I couldn't figure out how to get the element inside getApi

**Comment by amirHossein-Ebrahimi** [comment]
I courage you to add event listener by yourself in the custom component which you are making.
You can clear effect in useEffect cleanup.

For example, for the effect, we have in [examples directory](https://github.com/chintan9/plyr-react/blob/ef73315f7fb414db39f1fe5ebba88561b14da24a/example/src/custom-audio-player.tsx#L24-L41)

it is going to be something like this

```tsx
useEffect(() => {
   // ...
   const onEnded = () => console.log("I'm ended!")
   api.plyr.on('ended', onEnded)
   return () => {
     api.plyr.off('ended', onEnded)
   }
})
```


> How do I change the source?

> I can't figure out where in the code to change the source to override the defaultProps. I have the current audio src in Redux store, but can't seem to override it in the new code.

Could you please give us more discrete examples, any props you pass will going to be replaced by default props?
**NOTE**: We have a plan to remove the default props, in the near future

**Comment by bradrice** [comment]
Thanks for the example. For some reason it throws errors when I try that method.

It is thrown at this line:

`const { current } = ref as React.MutableRefObject<APITypes>;`

```
Uncaught TypeError: Cannot destructure property 'current' of 'ref' as it is null.
    at audioplayer.tsx:97:1
    at invokePassiveEffectCreate (react-dom.development.js:23487:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)
    at flushPassiveEffectsImpl (react-dom.development.js:23574:1)
    at unstable_runWithPriority (scheduler.development.js:468:1)
    at runWithPriority$1 (react-dom.development.js:11276:1)
    at flushPassiveEffects (react-dom.development.js:23447:1)
    at performSyncWorkOnRoot (react-dom.development.js:22269:1)
    at react-dom.development.js:11327:1
    at unstable_runWithPriority (scheduler.development.js:468:1)
    at runWithPriority$1 (react-dom.development.js:11276:1)
    at flushSyncCallbackQueueImpl (react-dom.development.js:11322:1)
    at flushSyncCallbackQueue (react-dom.development.js:11309:1)
    at scheduleUpdateOnFiber (react-dom.development.js:21893:1)
    at dispatchAction (react-dom.development.js:16139:1)
    at templatecontent.tsx:57:1
```

**Comment by bradrice** [comment]
I've basically copied your example code and found it works great, but I still cannot figure out how to pass props to the PlyrComponent instead of reading source at the top of the file.

**Comment by bradrice** [comment]
Never mind. I figured it out by adding props to the PlyrComponent. That works, unless you tell me I should be doing it another way.

```
const AudioPlayer = (props: any) => {
  const ref = React.useRef<APITypes>(null);
  console.log(props.audiosource);

  return (
    <div className="wrapper">
      {audiosource && (
        <CustomPlyrInstance
          ref={ref}
          source={props.audiosource}
          options={audiooptions}
        />
      )}
    </div>
  );
};
```

**Comment by amirHossein-Ebrahimi** [comment]
LGTM 👍🏻 , 
I'm going to close this issue, feel free to post us about example improvements, or your barriers.
It will hopefully be soon merged and published as a new version

**Comment by chintan9** [comment]
> Thanks, @chintan9.
> I'm not sure I get the whole idea well, but in a case, I get that right, you mean getting a branch from the latest `#developer` branch means we are going to release an alpha version of `plyr-react`. Is this correct?
yes
> In the case of releasing just consider we are going to use GitHub as a semi npm registry so it will download all project files from the HEAD of the branch, we are targeting. In case of solving this issue, I did it on my own and removed all non-related things even "devDependencies" from `package.json` I it can be solved well with strategies like the one [uWebSockets.js](https://github.com/uNetworking/uWebSockets.js#package-easily-installed) uses as its main release mechanism.

Okay

**Comment by amirHossein-Ebrahimi** [comment]
Nice work @chintan9 👍🏻
