### ISSUE TITLE
Plyr removes the inline style overflow: hidden; of a body tag when mounted inside a Modal.

### ISSUE THREAD

**Issue by prince272** [chintan9/plyr-react#736]
**Describe the bug**
Plyr removes the style attribute when mounted.

**To Reproduce**
1. Set an inline style in the body tag.
2. Mount Plyr component.
3. Check, I'd notice that Plyr did remove the inline body style.

**Expected behavior**
Plyr can modify but not to remove the inline style.

**Comment by amirHossein-Ebrahimi** [comment]
Hi @prince272, we never touch the inline style of the body in `react-plyr`, I believe It is the plyr issue. 
As you've already asked that there https://github.com/sampotts/plyr/issues/2417.
