### ISSUE TITLE
Sandbox with new api

### ISSUE THREAD

**Issue by bradrice** [chintan9/plyr-react#740]
I am not having the issue I showed you in the sandbox. Apparently, the issue with the fullscreen needing a wrapper is a problem in my own code. Here is a sandbox with the new api using usePlyr

https://codesandbox.io/s/plyr-react-new-api-forked-4cyfr?file=/src/App.tsx

For some reason the code hint is saying usePlyr is not exported, but it is working fine.

**Comment by amirHossein-Ebrahimi** [comment]
Hi @bradrice 
This is the working [codesandbox](https://codesandbox.io/s/plyr-react-new-api-forked-r0xo3?file=/src/App.tsx) if you want to test it further.

I will also search in the source code of `plyr`, seeking the necessitate of the wrapper element in the fullscreen mechanism. see more [in here](https://github.com/sampotts/plyr/blob/c2bfe489eab2c6f39335f0ede5a942bdefec11c9/src/js/controls.js#L67).


In case of quick testing, Could you memorize the `videosource` props? (`videosource` can be found in the code-sandbox I mentioned above.

```tsx
const videoId = useAppSelector(someStatePath)

const videoSrc = useMemo(() => {
  return { type: "video", sources: [{provider: "youtube", src: videoId}] } as const
}), [videoId])

// ...
<CustomVideoPlayer vodeoSrc={videoSrc} />

```

**Comment by bradrice** [comment]
Everything seems to be working for me with usePlyr function now. 

Unless others are reporting issues, it is probably time to move this out of alpha.

**Comment by amirHossein-Ebrahimi** [comment]
Hi @bradrice, I agree but there has been some type issue which is now fixed in the latest dev branch.

@chintan9 could we do one of these
- make the 4.0.0.alpha-1 a new released (non alpha/beta/rc version)
> It suffers from some typing issue which has now been fixed in dev
- update the dev and release the new beta version of the it, but keep the eye on dead line for releasing main version
> We should update github project section to make it clearer for developers what is project roadmap.
> NOTE: the new dev has been a really major change, it needs lots of testing, and it fixed lots of security issues meanwhile

> Also making thinks more robust and automated would always be appreciated.
> I would be happy if we can talk to change the devops side of the repo

**Comment by chintan9** [comment]
@bradrice & @amirHossein-Ebrahimi  

v4.0.0-alpha.3 has been released.  
https://github.com/chintan9/plyr-react/discussions/759

**Comment by amirHossein-Ebrahimi** [comment]
Thank you @chintan9,

@bradrice could you update package version to the latest and test whether it has the same functionality?
Also you might get type issue, feel free to post them here so we can fix them together.

**Comment by bradrice** [comment]
I've updated to alpha.3 and I'm not getting type errors in my code. Everything seems to be working ok.

**Comment by amirHossein-Ebrahimi** [comment]
Hey @chintan9, I think we can follow two-week principle.
If no one report bug on the latest release, we are going to publish a new (non-alpha) version on 24th April.

**Comment by chintan9** [comment]
Just before one week we will publish beta version also.

**Comment by realamirhe** [comment]
> Just before one week we will publish beta version also. 

Its a time to publish beta 😊.

**Comment by realamirhe** [comment]
Today is the biggest release we have ever made.

It would be great if you(@chintan9) could [contact me (📧)](mailto:amirhosseinebrahimi77@gmail.com) so we can manage a better release report or changelog for this particular release.

**Comment by chintan9** [comment]
@realamirhe Here we can talk https://t.me/+FZ3kOWROgsEzODYx.
