### ISSUE TITLE
Using event listener method plyr.on gives undefined method error.

### ISSUE THREAD

**Issue by kg-kartik** [chintan9/plyr-react#747]
```

const Test = () => {

   const videoSrc = {
    type: 'video',
    sources: [
      {
        src: 'yWtFb9LJs3o',
        provider: 'youtube',
      },
    ],
   };
    const ref = useRef();
    
    useEffect(() => {
        
        const plyr = ref.current && ref.current.plyr;

        console.log(ref.current,"ref");

        plyr?.on('timeupdate', () => {
            console.log(plyr.currentTime || 0);
        });

    }, []);

    return (
        <>
            <Plyr ref={ref} source={videoSrc} />
        </>
    );
}
```

Here, it gives error that plyr.on is not a function.
The ref.current property is being logged and is referring to the correct object but plyr is not available.

**Comment by amirHossein-Ebrahimi** [comment]
Hi @kg-kartik
Old Component is more designed for the static view, in case of dynamism could you please try our `usePlyr` hook in [4.0.0-alpha.1](https://www.npmjs.com/package/plyr-react/v/4.0.0-alpha.1).
Here is an example for a custom player which add event listener for `'ended'` event. [code](https://github.com/chintan9/plyr-react/blob/dev/example/src/custom-audio-player.tsx#L18-L50)
