### ISSUE TITLE
(JS-0113) Using named capture group is suggested in regular expression

### ISSUE THREAD

**Issue by chintan9** [chintan9/plyr-react#814]
## Description
With the landing of ECMAScript 2018, named capture groups can be used in regular expressions, which can improve their readability.

## Occurrences
There are 3 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/chintan9/plyr-react/issue/JS-0113/occurrences/](https://deepsource.io/gh/chintan9/plyr-react/issue/JS-0113/occurrences/)

**Comment by realamirhe** [comment]
Nice, thank you for sharing that, I didn't know about the deep source.
Don't you think it is over-engineering action for the first two reports?

```diff
 rules: [
      {
-       test: /\.(js|ts)x?$/,
+       test: /\.(?<scripts>js|ts)x?$/,
        exclude: /node_modules/,
        use: ['babel-loader'],
      },
      {
-       test: /\.(s?)css$/,
+       test: /\.(?<styles>css|scss)$/,
        use: ['style-loader', 'css-loader', 'sass-loader'],
      },
      {
_       test: /\.(png|jpg|jpeg|svg|webp|gif)$/,
+       test: /\.(?<formats>png|jpg|jpeg|svg|webp|gif)$/,
        use: ['file-loader'],
      },
```

**Comment by chintan9** [comment]
yes it is
