### ISSUE TITLE
(JS-D007) Bad usage of `RegExp#exec` and `String#match`

### ISSUE THREAD

**Issue by chintan9** [chintan9/plyr-react#816]
## Description
`RegExp#exec` and `String#match` are used when we need matches, but it is unnecessary to use when we just want to check if a matching pattern is present in the given string. So, it can cost more in performance of the application.

## Occurrences
There is 1 occurrence of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/chintan9/plyr-react/issue/JS-D007/occurrences/](https://deepsource.io/gh/chintan9/plyr-react/issue/JS-D007/occurrences/)

**Comment by realamirhe** [comment]
We have migrated the build system completely to rollup and esbuild, and plan to migrate to full swc in soon future. so it is no need to keep the config section at all.

https://github.com/chintan9/plyr-react/pull/821
