### ISSUE TITLE
Not working with React 18

### ISSUE THREAD

**Issue by bosbode** [chintan9/plyr-react#837]
React 18 is not an acceptable dependency. So the package only works with a downgrade to React 17.

**Comment by realamirhe** [comment]
Hey @bosbode, Thanks for the report
Support for React 18 has been added to the core `plyr-react` 
https://github.com/chintan9/plyr-react/blob/master/package.json#L157
but we need to update the documentation so we can release it.

@chintan9, could we have a new beta (RC) release sooner?

**Comment by chintan9** [comment]
@bosbode  Please refer this one https://codesandbox.io/s/plyr-react-new-api-forked-s8kksp?file=/src/App.tsx
