### ISSUE TITLE
Can't seem to get the package working and import errors for v5

### ISSUE THREAD

**Issue by maxhelsel** [chintan9/plyr-react#854]
I've been using the regular Plyr package and have it working. Was gonna give this a try, but I can't seem to get off the ground here.

Simply trying to import the following according to docs:
```

import Plyr from 'plyr-react'
import 'plyr-react/dist/plyr.css'

```

leads to this:

```

ERROR in ./src/components/main/views/videos/player/VideoPlayer.js 7:0-30
Module not found: Error: Can't resolve 'plyr-react' in [......my pathname......]

ERROR in ./src/components/main/views/videos/player/VideoPlayer.js 8:0-29
Module not found: Error: Package path ./plyr.css is not exported from package ..../node_modules/plyr-react

```

The packages are installed and present in node modules folder. I feel like this might be some webpack black magic stuff??

Not sure what the deal is - any thoughts or solutions are greatly appreciated!

Also, what is the benefit to using this package, "plyr-react" over the regular "plyr" package? I'm just trying to figure out if continuing with this is worth the extra effort considering I have "plyr" working already.

**Comment by chintan9** [comment]
@maxhelsel  Can you use v5.0.1 from now on? 

Let me know if have any issue right now.

**Comment by realamirhe** [comment]
I still have the issue.
Also, the suggestion for version `5.0.1` seems to be more than the dist directory itself

<img width="440" alt="image" src="https://user-images.githubusercontent.com/23579958/170810709-ba3a3a6b-ecb0-43fe-b28e-35670d99fd9a.png">

could you check what does the following command logs in the directory you want to publish

```bash
npx npm-packlist
```

**Comment by NTag** [comment]
On my side, v5.0.1 too, importing plyr-react works well, however importing the CSS file `import "plyr-react/plyr.css";` is broken:

```
Compiled with problems:

ERROR in ./src/components/ContentViewer/component.tsx 22:0-29

Module not found: Error: Package path ./plyr.css is not exported from package /Users/ntag/Documents/ntag/flocon/flocon/webapp/node_modules/plyr-react (see exports field in /Users/ntag/Documents/ntag/flocon/flocon/webapp/node_modules/plyr-react/package.json)
```
<img width="642" alt="CleanShot 2022-05-29 at 15 20 15@2x" src="https://user-images.githubusercontent.com/906276/170870951-69a18ae8-9433-4e6a-8c90-f858f3739af2.png">

It's just a CRA TypeScript app. Thanks!

**Comment by NTag** [comment]
Hum actually even if the import of `plyr-react` is working, when you try to use the `<Plyr` component, at runtime a crash happens because of this line: https://github.com/chintan9/plyr-react/blob/master/dist/esm/index.js#L87

<img width="501" alt="CleanShot 2022-05-29 at 15 40 18@2x" src="https://user-images.githubusercontent.com/906276/170871919-43ed5404-735b-4fad-a11d-b164be4a2c32.png">
<img width="539" alt="CleanShot 2022-05-29 at 15 40 35@2x" src="https://user-images.githubusercontent.com/906276/170871921-97cb4487-8324-40c1-bbdc-a39e39dad08a.png">

I guess there is an issue with the rollup config? Maybe https://stackoverflow.com/questions/67811412/rollup-react-17-with-new-jsx-transform-react-is-not-defined

**Comment by maxhelsel** [comment]
@chintan9 v5.0.1 allowed me to import the Plyr and its CSS - however, I then got same message @NTag received "React is not defined"

**Comment by realamirhe** [comment]
It seems there was a problem in tsx section for ESM modules

could anyone test the latest version

```
npx degit https://github.com/chintan9/plyr-react
cd plyr-react
npm install
npm run build
cd dist
npm pack

cd <your-project>
npm install <path to `plyr-react-5.0.0.tar.gz`
# or
# yarn install <path to `plyr-react-5.0.0.tar.gz` 
```

**Comment by SirVizzy** [comment]
I'm currently having the same issues for 5.0.1 where "React is not defined".

**Comment by NTag** [comment]
@realamirhe I just tested and it works! Both importing and using `plyr-react` and importing the css file in my CRA TypeScript project. I think you can publish a 5.0.2 version. Thanks a lot!

**Comment by realamirhe** [comment]
@chintan9 could you republish the package for `version 5.0.2`

```bash
npm build
np publish 5.0.2 --branch master --contents dist
```

**Comment by ThianHooi** [comment]
Is this issue resolved? I am facing the same issue using `version 5.0.1`. I think there is no new release yet. Or is there any workaround for now

**Comment by chintan9** [comment]
We are having issue with v5. 

Please use v4 until further notice

**Comment by chintan9** [comment]
v5.1.0 was published

**Comment by deadcoder0904** [comment]
can confirm. v5.1.0 works 🎉
