### ISSUE TITLE
ReferenceError: require is not defined in ES module scope, you can use import instead

### ISSUE THREAD

**Issue by altechzilla** [chintan9/plyr-react#866]
**Describe the bug**
ReferenceError: require is not defined in ES module scope, you can use import instead

**To Reproduce**
`"plyr-react": "^5.0.2",`

**Expected behavior**
For some reason, the library breaks the compiler when used inside a Node Module.

**Screenshots**
![image](https://user-images.githubusercontent.com/8274669/173056974-cb2896de-7767-43b7-9594-809f560fd9e4.png)

**Comment by realamirhe** [comment]
Hi @altechzilla 

Does the method mentioned in [this comment](https://github.com/chintan9/plyr-react/issues/854#issuecomment-1140487124) working for you?

I think the version 5.0.2 is reversion release on top of latest stable release for v4.
@chintan9 could we please update the repeated doc to notify users

**Comment by altechzilla** [comment]
It works if I remove “type”: “module” from the NPM module in which Plyr is being used. Otherwise, it throws that error. @realamirhe

**Comment by realamirhe** [comment]
I guess you are using plyr-react in non pure esm compatible environment.

The v5 designed to separate these field (esm, umd, system).
But in this case you might need to change the import path to system directory

"plyr-react/system"

**Comment by altechzilla** [comment]
Doesn't seem to work either, unless I'm missing something?:
![image](https://user-images.githubusercontent.com/8274669/173124097-d43305a5-a0ee-4a3c-92f9-7704630ba3d0.png)

**Comment by realamirhe** [comment]
I'm not sure, but it must not happen cause we are expose the whole lib.

It seems that the system is not recognized cause we didn't specify it implicitly in package.json, could you please add that field in package.json?
under '.' filed, and see wether it solves the issue, 


https://github.com/chintan9/plyr-react/blob/5c4bc57f9aa0612478ca54e571724169b565302e/package.json#L27-L32

Something similar to this:
```json
 "./system": { 
      "types": "./index.d.ts",
      "module": "./system/index.js",
      "import": "./system/index.mjs",
      "default": "./index.js"
 } 
 ```

**Comment by realamirhe** [comment]
sorry for inconvenient behaviour @altechzilla, in case you want to make you app up and running
You can use [version 4.0.0-alpha.5](https://www.npmjs.com/package/plyr-react/v/4.0.0-alpha.5) which is all the same version 5.0.2 except minor improvement in typing and build process. 

We will fix these issue ASAP, also PR is always welcomed

**Comment by altechzilla** [comment]
Okay, the old alpha worked. Looking forward for an update on v5. Thanks!

**Comment by realamirhe** [comment]
Hey @hacknlove, No unfortunately its not.

Currently we have issue in the packaging, @chintan9 might be better fit to clarify the issue.

**Comment by hacknlove** [comment]
is there any problem with this PR?

https://github.com/chintan9/plyr-react/pull/892

It seems it will solve the issue.

I think the only thing missing there is to build it, so the dist gets fixed too.

**Comment by sakib412** [comment]
I created this PR. https://github.com/chintan9/plyr-react/pull/892 
This fixes the issue. Don't know why they are not merging.

**Comment by chintan9** [comment]
> I created this PR. #892 This fixes the issue. Don't know why they are not merging.

Please add this line at 2 https://github.com/chintan9/plyr-react/blob/master/src/index.tsx

import PropTypes from 'prop-types'

**Comment by chintan9** [comment]
> > I created this PR. #892 This fixes the issue. Don't know why they are not merging.
> 
> Please add this line at 2 https://github.com/chintan9/plyr-react/blob/master/src/index.tsx
> 
> `import PropTypes from 'prop-types'`

I will merge it
