### ISSUE TITLE
PC vs Mac Autoplay

### ISSUE THREAD

**Issue by c-mella** [chintan9/plyr-react#867]
When testing the player on different browsers I've noticed that videos that are set to autoplay will work fine on Mac but PC browsers (namely Chrome and FF so far) will just have the poster image and wont play until clicked on. Is this a known bug (I'm on v4.0 alpha)?

**Comment by realamirhe** [comment]
Hey @c-mella , I'm thinking of a browser implementation limitation (design decision), but if it  is not relevant you can do following:

Based on this [plyr issue](https://github.com/sampotts/plyr/issues/1185), you can call `play()` on your own, for event implementation showcases you can take look at  our [example directory](https://github.com/chintan9/plyr-react/blob/master/example/react/src/audio-player/custom-audio-player.tsx) 

```jsx
useEffect(()=> {
    raptorRef.current.plyr.on('play', ()=>{
      raptorRef.current.plyr.play()
    })
})
```
