### ISSUE TITLE
CSS missing in CodeSandbox example

### ISSUE THREAD

**Issue by bradrice** [chintan9/plyr-react#890]
The typescript example is missing the css dependency.

https://codesandbox.io/s/plyr-react-new-api-forked-cg08k?file=/src/App.tsx

**Comment by realamirhe** [comment]
Hey Brad,

In version 5.0.1 it was imported from the package name direct descendant.

```tsx
import "plyr-react/plyr.css";
```

But it must return to its normal import path in the latest release.

**Comment by bradrice** [comment]
Thanks
