### ISSUE TITLE
require is not defined

### ISSUE THREAD

**Issue by tomtang1122** [chintan9/plyr-react#957]
on  v5.0.1

```
error - ReferenceError: require is not defined in ES module scope, you can use import instead
ReferenceError: require is not defined in ES module scope, you can use import instead
    at file:///xxxxx/node_modules/plyr-react/esm/index.mjs:80:21
```

**Comment by realamirhe** [comment]
Hey @tomtang1122 

We are a pure ESM package for now, although we have another build-type (e.g. CJS) ready to use we are not exposing them in the package.json.

You can read more about it [here](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c)

And if you tell us about your use case @chintan9 might consider providing our CSJ export for the next releases.

**Comment by tomtang1122** [comment]
thanks, but i hav anther question,

![image](https://user-images.githubusercontent.com/74886370/191672524-dc34ff61-9407-41f2-9ef2-265ff646efe7.png)
 console:  
![image](https://user-images.githubusercontent.com/74886370/191672792-5ba6f683-fd4c-4e47-8ad9-8e722ee6e328.png)
it is a Procy object

I can get the Plyr Instance when add the setTimeout
![image](https://user-images.githubusercontent.com/74886370/191673576-a2f0e855-04cd-42f6-8c7e-84082e8907f3.png)
![image](https://user-images.githubusercontent.com/74886370/191673668-206c6f3a-2d69-4c2f-8caa-1adad4d95573.png)

**Comment by realamirhe** [comment]
Hey @tomtang1122 , 
The reason you are getting the proxy in the first place cause for performance reasons we are not re-rendering the `<Plyr />` component in the first place and mainly using it for the Static contents.

For attaching event listeners, and working directly with the plyr instance you can work with out custom hook `usePlyr` instead

Here is the main proposal for the hook: https://github.com/chintan9/plyr-react/issues/678
here are [some examples](https://github.com/chintan9/plyr-react/tree/master/example/react) that may guide you within your implementations
