### ISSUE TITLE
Question: Change Player Style

### ISSUE THREAD

**Issue by Mondmarmelade** [chintan9/plyr-react#974]
Hey!
I am currently using the newest version of plyr-react (5.1.0).
The style of the navigation bar change between version v4 and v5. Is there a way I can use the v4 look with v5?
Thanks in advance.

### v5:
![v5](https://user-images.githubusercontent.com/91614367/197342848-af9868cd-92dc-4cc1-8928-89f52245d62e.png)

### v4:
![v4](https://user-images.githubusercontent.com/91614367/197342869-a50ce2a4-1e2a-4fac-88e1-5b8e875967dd.png)

**Comment by realamirhe** [comment]
Hey @Mondmarmelade, 
what version of plyr you have in your node_modules

```
cat ./node_modules/plyr/package.json | grep version
```

I'm not sure about plyr update in the code, guess didn't alter the plyr version, also we don't touch the minified CSS at all (just copy it to our dist through our pipeline)

https://github.com/chintan9/plyr-react/commit/673985bf8649601217c6fd711ac1e6299cb8dd3a#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L156

**Comment by Mondmarmelade** [comment]
Version 3.7.2 of plyr.
